### ISSUE TITLE
<table ?

### ISSUE THREAD

**Issue by codeskyblue** [mjmlio/mjml#100]
How can I write table. got many data to send.

**Comment by swibge** [comment]
Hi,

I just wrote a component for that, waiting to be approved and merged ;)
https://github.com/mjmlio/mjml/pull/101

**Comment by arnaudbreton** [comment]
Hey @codeskyblue, could you explain us a bit better what you're trying to achieve?

So far, regular HTML tables can be included by wrapping it up in an [`mj-raw`](https://mjml.io/documentation/#mj-raw) tag. From here, it should properly render.

Otherwise, yes as @swibge said, we started to implement such component, which is under review through PR #101. Feel free to have a look, share feedback and maybe contribute to it ;)?

Anyway, thanks for your interest in MJML.

Cheers

**Comment by iRyusa** [comment]
`mj-table` is part of `1.3` release :+1:

**Comment by codeskyblue** [comment]
:+1:
