### ISSUE TITLE
Is font-size:0px considered a SPAM trigger?

### ISSUE THREAD

**Issue by katart** [mjmlio/mjml#1045]
I recently received a code review from a large email marketing company and I was told to remove all references to `font-size:0px` because is was a SPAM trigger.

Has anyone else heard of this?

**Comment by ngarnier** [comment]
Hey @katart, `font-size:0px` is used here to avoid having spaces between sections, especially on older versions of Webkit.

While it can indeed be used by spammers to hide content, your email won't be flagged as SPAM because of that declaration. We've been using it in all the emails we send for our clients through Mailjet (as MJML is used in our own drag and drop editor) and haven't had any issue. If it was indeed
impacting deliverability, we'd have a problem 🙂.

**Comment by Pascal76** [comment]
Hello,

I confirm messages containing font-size:0px are blocked by freenet.de in Europe 
and probably some others ISPs.

**Comment by julien1619** [comment]
I can confirm that `font-size:0px` is triggering the anti-spam filter on Rspamd and some other ISP. For example some Sentry emails are going directly to spam because of it.

When I use MJML, my process is to remove all `font-size:0px;` and `font-size:0;` from the HTML, otherwise it will go directly to spam. In fact, `ZERO_FONT` will add 1 to the spam score, but it will trigger another rule `BAYES_SPAM` that will add 5.1 to the spam score.
