### ISSUE TITLE
win mail has excelled again

### ISSUE THREAD

**Issue by wireinet** [mjmlio/mjml#1106]
Hello! Ihave some errors in win10 client. please help with me understand to know in future
![preview](https://user-images.githubusercontent.com/23517333/38100568-65f4776c-3386-11e8-8a54-422978a88f62.jpg)
[index.zip](https://github.com/mjmlio/mjml/files/1860994/index.zip)

i include image camparison and project fire index.mjml (archived)

Thank you for mjml! its great! but win 10 mail client is Shit!

**Comment by iRyusa** [comment]
Hi @wireinet 

For the image cut-off, you have to reset the `line-height` to `1` on your table elements.
About the hero, you're using a fixed height that can lead to issue with outlook ( like this where your content doesn't have the same size on outlook due to font issues ) using a fluid-height, might fix it but not guaranteed.

**Comment by wireinet** [comment]
hello and thank you iRyusa! Thank again for you work and explanation!
