### ISSUE TITLE
Font-Family: Arial is causing a white border-bottom on Outlook 2016

### ISSUE THREAD

**Issue by qunvar-arora** [mjmlio/mjml#1192]
To help us help you, provide as much information as you can. You'll find below a template you can use to submit your issue, but feel free to remove any part that wouldn't be relevant here.
      
[Short description of problem here]
I have created a basic email in MJML which is using font-family=" 'Century Gothic', CenturyGothic, AppleGothic, Helvetica " for everything in my email from the <body> to <mj-text> and <mj-buttons> and it looks absolutely wonderful. I was asked by my Account Manager to change the font to Arial for everything in the email (which I did very carefully and simply) and all of a sudden there is a thin while line appearing at the bottom of my <mj-column> in the header <mj-section> of my email. The original font-family=" 'Century Gothic', CenturyGothic, AppleGothic, Helvetica " does not cause this problem as soon as I go back to using this. The issue only occurs when changing to font-family="Arial". I have looked at the HTML of both versions and they appear to be exactly the same the besides the font-family attribute change. I am using Pardot to send out these emails to the Outlook 16 client.

**Reproduction Steps:**

1. [First Step]
Change:
body {
      	font-family: 'Century Gothic', CenturyGothic, AppleGothic, Helvetica;
}

to

body {
      	font-family: Arial;
}

2. [Second Step]
Change:
<mj-attributes>
      <mj-text font-family="'Century Gothic', CenturyGothic, AppleGothic, Helvetica"/>
</mj-attributes>

to

<mj-attributes>
      <mj-text font-family="Arial"/>
</mj-attributes>

3. [Other Steps...]
Change for both <mj-button> elements:

<mj-button align="left" background-color="#ffffff" border="1px solid #009ADD" border-radius="50px" color="#009ADD" font-family="'Century Gothic', CenturyGothic, AppleGothic, Helvetica" font-size="16px" href="https://intelechygroup.com/" target="_blank">

to

<mj-button align="left" background-color="#ffffff" border="1px solid #009ADD" border-radius="50px" color="#009ADD" font-family="Arial" font-size="16px" href="https://intelechygroup.com/" target="_blank">

**Expected behavior:**

[Describe expected behavior here]
The expected behavior should match the screenshot here: https://ibb.co/edoOwJ

**Observed behavior:**

[Describe observed behavior here]
The observed behavior is showing a thin white line under my <mj-column> in the header <mj-section> here: https://ibb.co/mw5giy

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)
Here is the live MJML editor with the correct behavior on Outlook 16 and font-family="'Century Gothic', CenturyGothic, AppleGothic, Helvetica": https://mjml.io/try-it-live/SkDwTff0z

Here is the live MJML editor with the incorrect behavior on Outlook 16 and font-family="Arial": https://mjml.io/try-it-live/rJGXZmf0G

**MJML version:**

[Enter MJML version here]
Using "MJML App v2.8.0" which is using "MJML v^4.0.3" https://ibb.co/dEHK3y

**Email clients the bug is seen on:**

[Enter email clients names and versions here]
The bug is being seen on Desktop Outlook 16 using a Windows 10 machine.
I am using Pardot to send out these emails to the Outlook 16 client.

**Comment by kmcb777** [comment]
@qunvar-arora Hi, outlook has some issues with calculating heights, this kind of white lines can have multiple causes. 
The color of the line only depends on the <body> background, so it can't be fixed by wrapping your element inside of another element with the desired color as background.
I found a few workarounds that solve your problem, but you'll need to edit the html output : 
- If you manually set the height of the mj-column's <td>  that is in the outlook conditional, it renders fine
- On the <div> containing "Digital Health" that has `font-size:26px`, if you add `mso-ansi-font-size: 27px;` to the inline-style, it renders fine
- If you don't set `vertical-align: bottom` on the column, you don't get the white line.

Unfortunately all this values are situation-specific (i.e. here if you set font-size to 27px, then it renders fine without mso-ansi-font-size, and adding `mso-ansi-font-size: 28px` will bring back the white line...). Therefore these workarounds can't be adapted into a generic fix in mjml, so i'll close this one for now.
