### ISSUE TITLE
Better Responsive Tables

### ISSUE THREAD

**Issue by bkonia** [mjmlio/mjml#1241]
This issue was discussed in #197 and closed without any resolution. I'd like to continue this discussion, because presently, responsive table support in MJML is practically non-existent. If MJML is indeed a responsive framework, it should implement modern approaches to creating responsive elements. Using the `word-break:break-word` attribute seems like a cop-out and avoids addressing the issue of responsive tables. So how can we handle this? There are a few options:

1. Use `word-break:break-word`. This is the current behavior and the least desirable, because the text wraps in the middle of words and just looks horrendous. This is not what I expect from a modern responsive framework.

2. Use the solution described in [this article](http://maxdesign.com.au/articles/simple-responsive-table/) to create a horizontal scroll bar for just the table element. The author of the article acknowledges it's a rough solution, but it's certainly better than wrapping text in the middle of words. Horizontal scroll bars are never pretty, but so long as they're restricted to scrolling just the table element, rather than scrolling the entire document, this is an acceptable responsive strategy. I realize with MJML, we're dealing with nested tables, so the implementation is a little trickier than described in the article. I'm not a CSS expert, but It should be possible to accomplish this using something like `table-layout:fixed` in conjunction with `overflow-x:auto` and setting a max-width.

3. [Stack the columns](https://codepen.io/team/css-tricks/pen/wXgJww?editors=1100), so they become rows within the existing rows. This is an extremely elegant solution, though some users may prefer the scrolling approach.

There are other strategies discussed in the article I referenced, but I believe implementing these two approaches in MJML would represent a huge improvement over the current situation. I'd like to suggest adding a new `responsive` attribute for mj-table. The attribute options would be something like *word-break*, *scroll*, *stack*, allowing the user to decide which responsive strategy to use.

**Comment by iRyusa** [comment]
Hi, 
I don’t know if this is technically possible due to email context. As javascript is disabled and most of css attribute have a very limited support, I don’t think there’s much to do here... if there’s some technique « email friendly » we’ll be happy to try to implement it but given the example I don’t think it would work in older outlook clients

**Comment by bkonia** [comment]
Both the solutions I mentioned are pure CSS, no JS. Whether or not the CSS works in every email client, I don't know, but you could use a fallback approach. For example, the user could specify responsive="stack, scroll, word-break" and the styles would be generated using media queries to select the highest priority strategy that will work on the end user's device.

**Comment by bkonia** [comment]
It mentions jQuery only in the context of adding a cosmetic scroll bar for non-iOS browsers. The scrolling still works in those browsers, without the jQuery, but it doesn't display a visible scroll bar, so it may not be obvious to the user that he can scroll the table. Most people will figure it out and you could add some text or graphics to prompt the user to scroll the table, so even without the visible scroll bar, I still think it's a better approach than just arbitrarily wrapping lines in the middle of words.

I'm not suggesting this is easy, but if everything was easy, then we wouldn't need a framework, right? The point of the framework is to abstract away the hard stuff and make it more convenient to create responsive emails. I understand there may be some issues with CSS support in different email clients, but responsive tables are a pretty big deal, so I'm only suggesting your team should take a closer look at it, rather than just dismissing it as "too hard". I'm sure the existing approach can be improved in some way. I will look into this further on my end as well.

**Comment by iRyusa** [comment]
I think you clearly miss my point here. I said that it could be a good enhancement if the support and fallback is good enough. 

The main issue here is in your example some of described technique can’t work in an email context. We try as much as possible to abstract hard concept as we can but sometime it cannot be done.

Again, we’re totally ok on including such thing, if there’s some need, some working examples and decent fallback, as we provide today across all email clients. 

For the horizontal scrollbar, as of today you can override the behavior of it easily so it’s fine. And from an UX standpoint, I think that supposing that most of people will figure that they can scroll when it’s required is pretty naive.

The team resource is limited and we can’t take the time to figure out all the stuff we would want to. When using a table in a mobile context you should be aware of the limitations of screen space. So sometime a better approach is just to provide a more mobile friendly solution rather than getting stuck on a table layout.

**Comment by iRyusa** [comment]
I'm closing this issue because there's not really much we can do here. 

If you can provide a working demo in MJML of those behavior you want, with a decent fallback, we'll be happy to improve current `mj-table` implementation.

**Comment by arnaudlebon** [comment]
Hello, I had the same problem and the better solution I have found was to add an overflow to your table like that as mj-style attribute:

      table {
      	overflow-x: auto;
        white-space: nowrap;
      }

**Comment by SimonFricker** [comment]
Here is another solution. 

https://medium.com/@nathankeenmelb/bulletproof-responsive-datatables-in-html-emails-64248b9e18f5

https://codepen.io/nathankeenmelb/pen/QYggZX?editors=1010

**Comment by iRyusa** [comment]
I think it could be done in it's own community component for now, feel free to contribute so we can add it to the list ? If the result are good enough why not merging it in a future in mj-table/in core components

**Comment by SimonFricker** [comment]
I don't think I have the skills to do this.
