### ISSUE TITLE
MJML email not displaying at all (blank content) in Outlook 2016

### ISSUE THREAD

**Issue by ericnguyen23** [mjmlio/mjml#1282]
MJML email not displaying at all (blank content) in Outlook 2016 when using GreenRope CRM. I'm thinking it's related to GreenRope CRM, as the Litmus test email worked, but can't narrow down the issue.

**Reproduction Steps:**

1. Wrote MJML markup with MJML App for Mac
2. Copy and and pasted HTML to GreenRope CRM Software
3. Sent through GreenRope and not able to view content with outlook.

**MJML version:**

MJML App v2.8.0
MJML v^4.0.3

**Email clients the bug is seen on:**

Outlook 2016

**Comment by ngarnier** [comment]
As you said yourself, the issue sounds related to GreenRope CRM as the emails render well on Litmus. To confirm that, you can also try sending it via https://putsmail.com/ (do *not* check the box to inline CSS). 

As the issue is related to the CRM you're using, there's nothing we can do on our end. Please contact GreenRope CRM support, they are probably messing with the HTML.
