### ISSUE TITLE
How to make the 2 columns in same section having the same height

### ISSUE THREAD

**Issue by namKolo** [mjmlio/mjml#1322]
Currently, I need to design an email with the border between two columns. Now i set the `border-left` to the right column. But if the first column 's height is bigger than the second column's height. It 's not correct at all

** Expected **
![image](https://user-images.githubusercontent.com/16164170/44381187-54400200-a539-11e8-9692-eb79d40e95fd.png)

**Screenshots and GIFs**
![image](https://user-images.githubusercontent.com/16164170/44381140-193dce80-a539-11e8-8dc7-87a1348e6998.png)

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**MJML version:**
4.1.0
```
<mj-section>
// this one 's height is bigger
<mj-column><mj-text>abc</mj-text></mj-column>
// this one 's height is smaller
<mj-column border-left="1px solid grey"><mj-text>abc</mj-text></mj-column>
</mj-section>
```
 Any ideas how to do that? Please help me suggest ideas. Thanks all.

**Comment by ngarnier** [comment]
Hey, indeed columns are fluid so you can't force an absolute height. However there are workarounds, I'm thinking for example of one of those two:

- setting a border-right on the left column as it's the highest
- creating a gutter between the two columns and having the blue separator as a background-color instead of a border

Feel free to share your existing code so I can reuse it to show you how to use those workarounds.
