### ISSUE TITLE
MailChimp cuts off styles

### ISSUE THREAD

**Issue by SKROLL26** [mjmlio/mjml#1331]
I have an email designed with MJML and I use MailChimp to send my campaigns to subscribers. I tested it by sending test email from MC and found out that most of my styles don't work(exactly this `.navbar a:hover, .body a:hover{ color: #fbaf3f!important; } .button a:hover{ color: #ffffff!important }`), not all links work and column sizes have broken. Is it a problem with MailChimp, or there could be something I might have done wrong?

**Comment by ngarnier** [comment]
You can try sending with https://putsmail.com/ to confirm the issue is with Mailchimp, but Mailchimp is indeed known for messing with the HTML and breaking styles. Here is an [example issue](https://github.com/mjmlio/mjml/issues/844#issuecomment-338652365) (there are several) including an answer from Mailchimp about how they process the HTML.
