### ISSUE TITLE
Mailchimp template tags

### ISSUE THREAD

**Issue by markbloomfield** [mjmlio/mjml#135]
Further to our [discussion on Twitter](https://twitter.com/wondergryphon/status/709294071936905216), having the ability to use [Mailchimp template tags](http://templates.mailchimp.com/getting-started/template-language/) is invaluable.

Almost all newsletters I code, are for use in Mailchimp and are templates which clients will take control of to re-use for future use. Thus, being able to mark something as `mc:repeatable`, or `mc:editable`, is invaluable.

I tried and adding `mc:edit` to a `<mj-section>` borks it. I understand that's because it's not a catered for attribute, but surely you guys could add your own expected range of attributes, that would render out the Mailchimp tag in the output file?

Just as `full_width="full_width"` returns the relevant CSS, so to `mc:edit` would return that tag into the wrapping `<td>` etc...

Right now the system shows amazing promise and I'm amazed but its ease of use. But in production, not having Mailchimp support is a biggie :/

**Comment by arnaudbreton** [comment]
Hi @markbloomfield, thanks for moving the discussion here.

I see two main ways to approach this request from MJML perspective:
* Provide you with a way to pass attributes, outputted straight to the final HTML element. Something like `mj-attr-raw`, similar to `mj-raw` but for attributes. The main limit of that approach is since an MJML tag often leads to many HTML tags, we would not be able to position them anywhere else than the root element. Makes sense?
* Create your own components, inheriting from the MJML ones, supporting these attributes directly. We would love to help you build that and feature it to our developers community.
* Using raw HTML and position the Mailchimp attributes directly where you need, using `mj-raw` MJML tag. Definitely not my favorite solution since you'll loose all the advantages of MJML but still wanted to mention it here.

What do you think? Which one fit best your needs here?

Thanks for your feedback, appreciated!

**Comment by markbloomfield** [comment]
thanks @arnaudbreton. I think your first suggestion is closest to what I had in mind as a solution here.

I realise that the way the system compiles MJML results in a lot off code from a simple `mj-section` tag for example, but having the attribute apply only to the parent tag, is perfectly fine.

The main mailchimp tags that are needed when it comes to making re-usable templates, are `mc:edit="foobar"` and `mc:hideable` and `mc:repeatable`. Being able to put these attributes onto sections, columns and images would take MJML to another level in terms of usability.

Please shout if I can in any way contribute to this.. Happy to help :)

**Comment by iRyusa** [comment]
Duplicate with #200, closing this one because 200 have a implementation proposal
