### ISSUE TITLE
Ability to change background image render strategy for outlook

### ISSUE THREAD

**Issue by mastertheblaster** [mjmlio/mjml#1382]
Currently for adding global background image we do use `mjml-wrapper` component and specify the `background-url` property. This creates a nested table with Microsoft vml tags. However this breaks most of the layouts inside Windows Mail application.

I have found out that approach mentioned here https://backgrounds.cm/ works.

Currently i see only such a fix:

`<mjml-wrapper background-url="" no-vml="true">...</mjml-wrapper>`

By adding a prop `no-vml` which should skip VML tags.
In such case it would be my application responsibility to manage the background for outlook properly.
And also we could introduce another mjml component `<mjml-outlook-full-page-bg src="" color=""/>`.

What do you think? Could create a PR if interested.

**Comment by iRyusa** [comment]
Well I think it's really counter productive here, I let the issue open to let the community discuss about this. But we have only "one" attribute specific to outlook to manage the responsive behavior on outlook.com.

> This creates a nested table with Microsoft vml tags. However this breaks most of the layouts inside Windows Mail application.

Do you have any example about this, because as far as we tested I didn't expected any issue, the only issue being the padding being not really well respected because of a bug in the word engine (cf https://github.com/hteumeuleu/email-bugs/issues/32) 

As we want hide those hacks for MJML users and have a clean semantic based language, I feel this is counter-productive to have such thing. mj-wrapper with full-width & background image should basically does the same as backgrounds.cm code.
