### ISSUE TITLE
Dynamic text override for mj-includes

### ISSUE THREAD

**Issue by matthewahillman** [mjmlio/mjml#1415]
We use a modular setup with building emails, each section that makes up a module is in it's own file. Things like headers etc are great being able to pull in an include and not have to see massive blocks of code. What I would like to be able to do is to have a dynamic text section in the includes file which would allow me to override the text in the main file without pulling in the whole module. 

**For example:**

Say in your module there is a block of text that is a placeholder. I'd like to be able to put a mj-dynamic or something within the text or image and then be able to override that within the include.

**In the include file:**

`<mj-text mj-dynamic-class="headingUpdate" mj-class="heading">This is the old heading</mj-text>`

Then in the main file pulling that block in.

`<mj-include path="image-left-normal-stack.mjml"><mj-dynamic-class"headingUpdate">New heading</mj-dynamic>`

If there is no mj-dynamic the page pulls through whatever was set as the text or image.

Why would I want this? This would stop users from getting confused with the code, would make editing the copy in modules easier and would allow people with very limited coding update the modules without breaking anything.

**Comment by ngarnier** [comment]
From what I understand what you want is a templating language. We don't plan to add any templating features in MJML, because: 

- the role of MJML is making the responsive email part easier, and we want to stick to that
- adding templating features would complexify the code base a lot
- there are a lot of tools that already handle that very well (handlebars, pugjs, etc)

However you can totally use a templating language with MJML!
