### ISSUE TITLE
Nesting on documentation

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml#1425]
**Describe the bug**

There's a empty section on docs: [nesting](https://mjml.io/documentation/#nesting)

**To Reproduce**
1. Go to the documentation site
2. look for nesting

**Expected behavior**

To find something about nesting.

**Comment by kmcb777** [comment]
Hi @robsonsobral Thanks for reporting this !
Nesting just means that mj-components can be nested in each other, but it's true that just the example  on the right doesn't explain much, so we'll remove this since there are already examples for each mj-component, that shows where they are supposed to be placed.
This part of the doc is handled by the website, not this repo, so i'll close this issue.
