### ISSUE TITLE
Add classes to mj-elements on render

### ISSUE THREAD

**Issue by muuvmuuv** [mjmlio/mjml#1458]
**Is your feature request related to a problem? Please describe.**

I'm currently styling my first MJML for mobile clients and encountered a problem with `mj-spacer`. I would like to half the height of it on mobile, this would work fine with CSS and a class I could give each one, but I would like to ask if you would add classes to mj-elements to the cors so I could style them without giving them a class by myself. I think this would improve the work with MJLM a lot.

```html
<div style="height:20px;" class="mj-spacer"> &nbsp; </div>
```

**Describe alternatives you've considered**

A breakpoint attribute which holds styles or the specific attribute for the breakpoint which is set in the head.

```html
<mj-spacer height="20px" mobile-height="10px" />
```

**Comment by dalefish** [comment]
Use css-class on the element <mj-spacer css-class="spacer" />

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment]
Well, that's a tough one to respond. We would love to have those `mobile-` or `desktop-` alternative (not sure about the syntax) but this would add a lot of complexity for MJML to manage it.

Consider that if you have a mobile height, you'll have to use it as default (because MJML is mobile first) then create a media query for this element that will apply for desktop clients. Then come outlook, we need to do a specific conditionnal mso block to be properly displayed in Outlook Desktop.

About adding local class for each element, I don't think this is a good idea, because it would be useless  more than 90% of the time because it will be global for every mj-element, and you most likely want to have specific things for 10 mj-text and not globally. It will increase drastically the final HTML output, and email could be cutted in some clients

Note that you can add a css-class globally to every-element if you want already : https://mjml.io/try-it-live/r16LrsDxE

**Comment by muuvmuuv** [comment]
@iRyusa Okay, I understand that is correct, giving all the same class makes not much sense, but I think it would create a big benefit for MJML to have something like breakpoint attributes. Atm yeah, I use `css-class` but I just say it would be nice to have this as an improvement.

**Comment by iRyusa** [comment]
Yup, but that would still require a lot of effort to keep consistency across device/clients

**Comment by iRyusa** [comment]
I don't think we have much to add on this topic, I'm closing the issue.
