### ISSUE TITLE
Versionning mistage and mj-section error

### ISSUE THREAD

**Issue by liminspace** [mjmlio/mjml#1475]
Hi!
I install an environment:
```
$ nvm install 8
$ nvm use 8
$ npm install mjml@4.0.5
$ node_modules/.bin/mjml --version
mjml-core: 4.3.0
mjml-cli: 4.3.0
```

Then I try to compile simple MJML
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>MJMLv4</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
and I get the error `mj-section cannot be used inside mj-body, only inside: mj-attributes, mj-container, mj-wrapper`.

But it worked well several months before as I use it on unittests in my `django-mjml` library.
See travis log https://travis-ci.org/liminspace/django-mjml/builds/475281501

I have 2 questions:
1. Why I get mjml-core and mjml-cli 4.3.0 if I install mjml@4.0.5? Does versioning work or not? I had similar problem couple years ago. Hasn't it still done?
2. Why I get error if my MJML is correct? Or do I do something wrong?

**Comment by iRyusa** [comment]
Hi,

Version wasn’t pinned properly until mjml 4.3 so that’s why you have the 4.3.

About your error it seems that you have some package in mjml 3 somewhere conflicting. Try to remove any global mjml related package that could conflict with local install

**Comment by liminspace** [comment]
There are not any global mjml related packages. There aren't anything to remove! As I wrote abowe, it is a clean system, a docker container, where unittests are running. Here is the travis file https://github.com/liminspace/django-mjml/blob/develop/.travis.yml
@iRyusa **the problem hasn't been resolved yet**.
Please, help me to resolve this problem. I want to have possibility of testing my django-application using different MJML's versions.

**Comment by iRyusa** [comment]
There's clearly an issue on your installation as MJML4 doesn't have any reference to `mj-container` in the codebase anymore (only on migration tool).

**Comment by liminspace** [comment]
No, travis runs test in a new clean container.
This problem is ONLY when MJML 4.0.5 is installed. You can see here https://travis-ci.org/liminspace/django-mjml/builds/475281501

But it worked without any problem a month ago https://travis-ci.org/liminspace/django-mjml/builds/464682620

**Comment by liminspace** [comment]
We had a similar problem before and you said it had been fixed https://github.com/mjmlio/mjml/issues/349

**Comment by iRyusa** [comment]
We've moved on lerna on 4.0, we had some issue where version were not properly pined as it was in 3.X branch. We did update our config in 4.3 to now ensure that the strict version is used until 4.3 release, because of that installing previous version prior to 4.3.0 is really messy (see https://github.com/mjmlio/mjml/issues/1442#issuecomment-443453398 for the solution to install previous version, it requires a special package json and only npm, as yarn doesn't want to behave the same).

I think it could be related to an issue we had in 4.0.5 that has been fixed in 4.1 & onward, as it's a validation issue.

We can't fix 4.0.5, so you should ignore those version, and skip every version between 4.0 to 4.3.0 where the version pinning actually works fine now.

**Comment by liminspace** [comment]
OK, I'll remove testing of different versions of MJML, but it is not very good solution.

**Comment by iRyusa** [comment]
It’s a bug in that particular version that broke the validation we can’t really do something about it.
