### ISSUE TITLE
Documentation contains confusing component names

### ISSUE THREAD

**Issue by KempWatson** [mjmlio/mjml#1480]
The MJML documentation is rife with description of elements/components such as "mjml-column" when the components are actually like "mj-column". There are many dozens of such incorrect references, as a matter of fact _every single_ component is mislabelled.

Very confusing...

**Comment by ngarnier** [comment]
The fact that _every single component_ is mislabeled is actually because it's not. If you look at https://github.com/mjmlio/mjml/tree/master/packages, you'll see the name of each package indeed starts with `mjml-`. 

However, the syntax when coding in MJML is indeed to start the component names with `mj-`. We could update the doc to reflect the name of the component rather than the package name.

**Comment by KempWatson** [comment]
Ah, understood. Unless I missed the explanation of the difference, though, it might be helpful (for newbies like me at least) to be clear on the difference between development terms and user terms. Thanks!

**Comment by Martin-Pitt** [comment]
Ohhh, yeah, I just picked up MJML recently and found this very confusing and wasn't sure if I did something wrong.

Could this be made consistent at least with one or the other? Even the navigation has "mjml-body" after "mj-head" in the Components section.
