### ISSUE TITLE
Does this work with gmail client?

### ISSUE THREAD

**Issue by petervijeh** [mjmlio/mjml#1499]
its not really clear from the support section and I don't want to invest time in this framework if it won't really work for the various clients I need to support.

**Comment by ngarnier** [comment]
So if I understand correctly, you don't want to invest time (~1 minute) to test a framework that other people have invested time in (~countless hours), so someone else should invest more time answering your questions because you don't want to do a search or a test yourself? The way you approach open source is pretty interesting (and wrong).

Good luck!
