### ISSUE TITLE
Rendering problems (columns & images) in Outlook app [Win10 version]

### ISSUE THREAD

**Issue by DallOner** [mjmlio/mjml#1507]
**Describe the bug**
In the native Outlook application (Windows 10), certain columns are not rendered properly, they are not shown aligned with the structure of raised columns and some images are shown in their original size when they should be displayed on a smaller scale and fit the expected design.

**To Reproduce**
Simple, open a mail sended with Outlook app (Win10 version) and see the error.

This is the code used to make the mockup:
[MJML Code (via Pastebin)](https://pastebin.com/iwu4S7RC)

**Expected behavior**
[Outlook Web version (expected result)](https://imgur.com/ZXxJfYK)  
[Gmail mobile result](https://imgur.com/eTRq9bv)

**Real behavior in Outlook native app**
[Actual Outlook in Win10 render](https://imgur.com/Mam1JQm)
[Footer in other mockups](https://imgur.com/ZmcqPeQ)

**MJML environment:**
 - OS: [e.g. Ubuntu 18.04]
 - MJML Version [e.g. 4.2.0]
 - MJML tool used [e.g MJML App via NPM commands]

**Additional context**
I have tried to modify the MSO conditionals specifically in width handlers, passing them from pixels to % but without success results. In addition to placing certain rules of styles in-line to correct the final transpile, as a result of this last the interpreter of Outlook reads the rules in a totally erroneous way.

**Comment by ngarnier** [comment]
hi @DallOner, your markup is invalid:

- line 251, you have a section with 2 columns of each 100%. The columns inside a section shouldn't be more than 100% in total
- line 258, you should rather use 4 columns with an image in each instead of just putting image tags inside a text tag like this
- line 263, you missed to close the column tag

Fixing those points should fix your problem. 

PS: you can share MJML content with the try it live directly: https://mjml.io/try-it-live/HJAOJSvNV

**Comment by DallOner** [comment]
Hi @ngarnier thanks so much for the fixes! but still a little broken in Outlook app.
[Code with Fixes HERE](https://mjml.io/try-it-live/HkO5vBDVN)

Updated Real behavior with Fixes:
[Columns Desaligment](https://imgur.com/tTK3ieF)
[Button & Footer](https://imgur.com/9UuwCjV)

The misalignment of the columns would appear to be because the outlook interpreter rendered as if it were a mobile resolution. On the other hand, I do not know why the interpreter reverts the button in that bad way, without any apparent style.

**Comment by ngarnier** [comment]
The fact that the columns stack is because Outlook app shows the mobile version by default. You can either:
- keep columns side by side in mobile instead of having them stack using [mj-group](https://mjml.io/documentation/#mjml-group). If you do so, columns will stay side by side on mobile devices as well in all emails clients (which you might want as you have a table layout)
- force Outlook app to keep columns side by side using `<mjml owa="desktop">`. If you do so, Outlook app will keep columns side by side and other desktop clients as well, but mobile clients will display them as stacked

For the button, please use [mj-button](https://mjml.io/documentation/#mjml-button) instead of faking a button with a link.
For the footer, not sure what's happening as I don't have issue (see [here](https://app.emailonacid.com/app/acidtest/tDvHaS5ul654YEh3ZKynrHNArGLXVhAwojbGrtuBn9FvE/list)) apart from the fact they stack but my solution above will fix that too.

**Comment by DallOner** [comment]
Hey man, you are the best! thank you very much, all the corrections have been successful, the footer theme will be fixing to place a single image in that column. Everything else works 100/100. thanks again!

**Comment by ngarnier** [comment]
Are you referring to Outlook.com or to a desktop version of Outlook? If so, which version?

If Outlook.com, just force the desktop layout for this client with `owa="desktop"` on the `mjml` tag: https://mjml.io/try-it-live/SJzTvcvDS.

**Comment by Kureyko** [comment]
@ngarnier desktop version of Outlook on Windows 10. I tried 3 different html signatures, none of them works as should (columns).

**Comment by ngarnier** [comment]
Sections are like rows in your email, while columns are columns inside those rows. As a consequence, the sum of all columns inside a single section should not amount to more than 100%, which is not the case in your MJML. 

For example, if you look at the section starting line 58, you can see it's made of a first column whose width is 100%, and many other columns.

**Comment by Kureyko** [comment]
@ngarnier  i give you my example:
Here is the code of example e-mail [signature](https://pastebin.com/ZyTuHgzQ)
Image should be next to text. Its perfectly working on [GMail (screenshot)](https://paste.pics/6SG33) and Outlook [Mac OS (screenshot)](https://paste.pics/6SG3F).
And on Windows Outlook Desktop App we have this [incorrect result](https://paste.pics/6SG40).

And this example [https://mjml.io/try-it-live/SJzTvcvDS](https://mjml.io/try-it-live/SJzTvcvDS) also is incorrect in Windows Outlook Desktop App [(screenshot)](https://paste.pics/6SG87).

**Comment by ngarnier** [comment]
I already explained the issue, I don't know how else to word it. 

**The sum of the columns inside a section should not be greater than 100%.**

Fix your code accordingly.
