### ISSUE TITLE
mj-section Vertical align is not working

### ISSUE THREAD

**Issue by roman-savitskyi** [mjmlio/mjml#1534]
**Describe the bug**
When I try to add vertical-align to section, it is not working. Is it incorrect in documentation or?

**To Reproduce**
1. https://mjml.io/try-it-live/BJ7-8C9IV

**Expected behavior**
All columns in section should get vertical align. As it works on CSS tables

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.3.0

**Comment by kmcb777** [comment]
Hi @roman-savitskyi you have to set vertical-align on at least two columns, because they align relatively to each other

**Comment by roman-savitskyi** [comment]
Hello

https://mjml.io/try-it-live/BJ7-8C9IV
Please check once more.
Section with middle. 2 from 3 columns too and it isn't work.

Your idea right now:
1) Top, bottom works as well.
2) Middle works if biggest height column has middle align

Aligning in section doesn't works at all!

**Comment by kmcb777** [comment]
If you want them to align relatively to the middle column you need to define vertical-align on this one too. It works the same in regular css

**Comment by roman-savitskyi** [comment]
Question here another
https://mjml.io/documentation/#mjml-section

Vertical align in section. 
As i understand correct, it will not at all. Am I right?

If i want to organize align, i should use ONLY column vertical-align prop

**Comment by kmcb777** [comment]
Ah ok i see what you mean, since you set vertical-align on the column in your first example i thought you talked about setting it on the columns.

Actually vertical-align shouldn't even be here on mj-section, thanks for reporting this.

The html generated by a mj-section contains multiple tables nested in each other, so it's impossible to naturally behave like a td in a table. The only way would have been to manually transfer the attributes from the section to its children, but we think it's doesn't add much value compared to setting it directly on the columns, so we'll remove it completely.

**Comment by roman-savitskyi** [comment]
Thanks for answers. 
Please update documentation or i should prepare PR for u?

**Comment by kmcb777** [comment]
If you have time to spare for a PR it would be much appreciated :)
