### ISSUE TITLE
Remove default inline font-size:13px set on mj-columns

### ISSUE THREAD

**Issue by viktorix** [mjmlio/mjml#1560]
**Describe the bug**
By default, mj-column gets inline font-size:13px set but since font-size isn't available for mj-column it can't be deleted/overwritten. Any specific reason for this?

**To Reproduce**
1. Create simple MJML template with mj-column
2. Copy HTML
3. Check inline styles of column DIVs

**Expected behavior**
Either mj-column shouldn't have font-size set by default or allow font-size attribute for mj-column.

**MJML environment (please complete the following information):**
 - OS: Win 10
 - MJML 4.3.1
 - MJML App 2.11.0
- this also happens in Visual Studio Code with MJML extension.

Thanks.

**Comment by iRyusa** [comment]
Well that one is really weird as it should be font-size:0; instead, let's
fix this for 4.4

**Comment by YasiOnFire** [comment]
#1563 
I think this kinda breaks mj-raw, or am i mistaken? Should one expect to explicitly set font-size in the raw html code to overwrite font-size 0 from mj-column? (testing on MJML 4.4.0-beta.2)

**Comment by iRyusa** [comment]
Dunno if "break" is the best word for this, but yeah it will change the behavior of it.

You would just need to add font-size on content inside mj-raw as it's done already in any content tag in `mjml` so it's just about following best practice ? Most of `mj-raw` are related to templating stuff so it shouldn't be a real issue here. 

We'll add a warning on the changelog about this anyway

**Comment by Snowirbix** [comment]
Of course it breaks mj-raw, can we add a comment on https://mjml.io/documentation/#mj-raw ?
