### ISSUE TITLE
mjml@4.4.0-beta.1 tagged as latest in npm

### ISSUE THREAD

**Issue by ctavan** [mjmlio/mjml#1605]
**Describe the bug**
`mjml@4.4.0-beta.1` has been published with the `latest` tag to the npm registry. This is unfortunate for users with automated dependency updating tools which may install this beta version instead of the latest stable version.

**To Reproduce**
`npm info mjml`

<img width="800" alt="Screenshot 2019-05-21 14 28 48" src="https://user-images.githubusercontent.com/508118/58096205-d480ba00-7bd4-11e9-85cc-5085fdb5eb8f.png">

**Expected behavior**
Have `v4.3.1` tagged as `latest` dist-tag in npm (probably a bugfix version bump required) and the beta as `next` or `beta`.

**Comment by iRyusa** [comment]
Hi, 

Well when I published the beta I fucked up. Used the wrong lerna option, and then it was too late to unpublish it when we saw it. You can still install mjml 4.3.1 with `npm install mjml@4.3.1` the dependencies are now fixed.

I think future beta will still be flag as latest now ( at least if we're confident about the stability and the changes ). And it help us to find bug instead of adding a dist tag that almost no one use.

>  This is unfortunate for users with automated dependency updating tools which may install this beta version instead of the latest stable version.

About this, doesn't it follow the `~` in the `package.json` ?

**Comment by ctavan** [comment]
Thanks for the feedback @iRyusa!

Regarding your comment:

> About this, it doesn't follow the ~ rules in the package.json ?

It is true that most package-updaters (like renovate bot or greenkeeper) won't suggest upgrading to semver unstable release tags (i.e. those with a `-suffix`), I got that wrong in the initial report.

In fact I was stumbling upon the issue when running a manual `yarn upgrade-interactive --latest` which in the case of `mjml` suggests to install the beta version.

As a user of packages in the npm registry I just find it really confusing to have a beta version being tagged as `latest`.

My expectations arise from what is written in [the `npm` documentation which states](https://docs.npmjs.com/cli/dist-tag#purpose):

> By default, the latest tag is used by npm to identify the current version of a package, and npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag. Typically, projects only use the latest tag for stable release versions, and use other tags for unstable versions such as prereleases.
> …
> By default, other than latest, no tag has any special significance to npm itself.

So since the `latest` tag has special meaning in npm I would find it really helpful if `mjml` would also follow this pattern.

Any chances the `mjml` package will follow this pattern in the future again? After all if you're confident enough that what you are currently releasing as `beta` is stable enough so that first time users of `mjml` will get that version when they run `npm install mjml`, why not just publish that version as `latest` without `-beta` suffix in the first place?

**Comment by iRyusa** [comment]
> Any chances the mjml package will follow this pattern in the future again? After all if you're confident enough that what you are currently releasing as beta is stable enough so that first time users of mjml will get that version when they run npm install mjml, why not just publish that version as latest without -beta suffix in the first place?

Well to be fair, it's a better way to flag the release as "not final, but nearly done". It's more a RC rather than a Beta, and it allows us to get more feedback from new users and from people who upgrade it too.

> In fact I was stumbling upon the issue when running a manual yarn upgrade-interactive --latest which in the case of mjml suggests to install the beta version.

Yup it will just give you the latest version available for the tag so it will be considered as the latest available.

NPM versioning is a pain, as you have a small window to correct yourself. We'll keep the next beta in latest branch for now, we'll see then after 4.4.X to go back to the `next/prerelease/...` or any tag if it has more sense semantically speaking.

The drawbacks will be that we won't have many bug reports... but that's how open source works I guess :)

Will close the thread because I don't think there's much to say, we'll get back on a tag for further beta/pre-release/rc after 4.4.0 release so it won't confuse anyone 👍
