### ISSUE TITLE
How to get text wrapped around element (floating text around image)

### ISSUE THREAD

**Issue by bilke** [mjmlio/mjml#1627]
**Is your feature request related to a problem? Please describe.**
I would like to have small images (e.g. 25% in width) and text wrapped (floating) around that image. I HTML it would look like this:

```html
<img style="float: left; width: 25%; margin: 0 16px 10px 0;" src="...">
<p>...</p>
```

Im mjml I tried this:

```html
<mj-style>
      .float-left {
        float: left;
        width: 25%;
      }
</mj-style>
...
<mj-image css-class="float-left" src="..."></mj-image>
<mj-text>...</mj-text>
```

But this does not work as every component is wrapped in an `<tr>` table row HTML tag.

**Describe the solution you'd like**
Is it really necessary to have everything in tables? Can I somehow disable the wrapping of mjml components in table `<tr>`-elements?

**Comment by iRyusa** [comment]
> Is it really necessary to have everything in tables? Can I somehow disable the wrapping of mjml components in table <tr>-elements?

Well some of desktop clients like Outlook has a terrible support of CSS. So that's why there's a lot of table :) 

I would use something like this https://litmus.com/community/discussions/1543-responsive-allowing-text-to-flow-around-images#comment-4930 the post is a bit old, but it will do the job, you can just use this inside a standard mj-text.
