### ISSUE TITLE
Responsive columns when specifying column widths

### ISSUE THREAD

**Issue by misterjrtaylor** [mjmlio/mjml#1642]
When specifying column widths, images are rendered at less than the width of the column when on mobile. 

I'd like to stack the columns on mobile with the image being full width, and displayed as a 33/67 split on desktop (on Foundation this would be with the `.small-12 .large-4` classes on the image column and `.small-12 .large-4` on the text column).

The code I'm using, on the Try-it-live editor is:

    <mj-section>
        <mj-column width="33%">
            <mj-image src="..." />
        </mj-column>
        <mj-column width="67%">
            <mj-text><p>some text here/p></mj-text>
        </mj-column>
    </mj-section>

Removing the widths and using a 50/50 split works as expected.

Thanks.

**Comment by iRyusa** [comment]
You have to use fluid-on-mobile attribute to have a full width image in mobile.

**Comment by misterjrtaylor** [comment]
Thank you - fixed (must remember to thoroughly read the docs).

**Comment by GregoireGonzalez** [comment]
> You have to use fluid-on-mobile attribute to have a full width image in mobile.

Is there the same for columns ? I have a two columns section (33% & 67%) on desktop and I want them to be both at 100% on mobile (meaning two lines instead of one in desktop). I didn't find the solution...

I have something like this

`<mj-section padding="0 0 20px">
            <mj-column padding="0 10px 10px" vertical-align="middle" width="35%" >
            </mj-column>
            <mj-column padding="0 10px 10px" vertical-align="middle" width="65%">
            </mj-column>
        </mj-section>`

Please appreciate my Microsoft Paint design
![image](https://user-images.githubusercontent.com/41725601/158449808-da963217-ad02-4d6c-809d-458e48532330.png)
