### ISSUE TITLE
make social icon color settable (always white until now?)

### ISSUE THREAD

**Issue by npracht** [mjmlio/mjml#1656]
**Is your feature request related to a problem? Please describe.**
I wanted to change the color of the icon itself, not the background color of the icon. I couldn't find a way to mange it.

**Describe the solution you'd like**
Add a `icon-color` css element ?

**Comment by kmcb777** [comment]
Hi @npracht  You can change the icon color, background-color is actually made for this, like this : https://mjml.io/try-it-live/HJstr_OfB
(This works only because the social icons we provide are natively transparent and the color is really applied as a background-color, thus the attribute name. There is no way to change an image's color with outlook-supported css)
Does it suit your needs ?

**Comment by npracht** [comment]
Nope ! In case you're on a black backgrounded section, and white social, how do you manage it ? i'd like that the logo (F of Facebook, In of Linkedin) is in black.

**Comment by kmcb777** [comment]
In this case you'll have to use your own icon, with the `src` attribute (https://mjml.io/try-it-live/HJstr_OfB)
The `f` is white in the provided image, and as i said there is no way to change an image's color with outlook-supported css.
