### ISSUE TITLE
XML namespace for MJML

### ISSUE THREAD

**Issue by Atulin** [mjmlio/mjml#1657]
**Is your feature request related to a problem? Please describe.**
PHPStorm doesn't understand MJML and always fills my code review with warnings and errors due to that.

There has been a language plugin in the works (#53), but I only managed to find two repos (a Github repo and its direct clone on Gitlab), both filled with nothing but a blank scaffolding, so it's safe to assume nobody cares about supporting IntelliJ IDEs.

**Describe the solution you'd like**
An XML namespace definition of MJML. That way, declaring `xmlns=""` for `<mjml>` tag might make the IDE accept the syntax as up to spec.

**Describe alternatives you've considered**
A proper language plugin, but it seems it's not happening.

**Comment by iRyusa** [comment]
Well I don't think a namespace file would really do anything here, you should switch to HTML formatter instead of XML (MJML isn't XML compliant anyway, and you will have more confusing errors).

You should follow this instead: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000238699-MJML-reformat-code?page=1#community_comment_360000051400 it looks like adding custom HTML tag is enough.

**Comment by Atulin** [comment]
Adding custom HTML tags would fix it, yes, but it pollutes HTML autocompletion, making all `<mj-` tags appear when `<m` is typed in.

If nothing more can be done, I guess I'll just slap `<!--suppress ALL -->` on top of each file and be done with it ¯\\\_(ツ)_/¯
