### ISSUE TITLE
Responsive approach

### ISSUE THREAD

**Issue by kickbk** [mjmlio/mjml#1667]
This is a question. Not a bug.
MJML adopts the approach of extending all columns (mj-column-per-whatever) to 100% by default, and for responsive purposes adding @media queries with the mobile width overrides.
So basically the idea is "Let's stretch to 100%. It will work on mobile. Then if we are viewing on a large device override with the "per-X" values.

Makes sense, however, if the client (say Mailinator for example) strips of the styles from the head, then it all looks wrong. May I ask why MJML did not take the opposite approach of first assigning the proportional values to the columns and only overriding on Mobile to 100%?

**Comment by ngarnier** [comment]
Hey @kickbk, the reason to choose this approach (which is a mix of the fluid-hybrid and mobile-first approaches) is that desktop clients support better media queries than mobile clients (+ the possibility to use Outlook conditional comments for Outlook clients).

Also, consider this: 

- showing a mobile-first layout on a desktop client (in case responsive styles are not supported) means you'll have a one-column layout. Not optimal, but still totally readable.
- showing a desktop-first layout on a mobile client (in case responsive styles are not supported) means the user will either have to scroll horizontally or to zoom out (because the layout is 600px). Hardly readable.

Hope that answers your question :-)
