### ISSUE TITLE
Columns on outlook desktop break to 100%

### ISSUE THREAD

**Issue by lRlevolution** [mjmlio/mjml#169]
As you can see ( http://awesomescreenshot.com/0ea5r3eg2d ) for some reason the columns break and dont stay at the % they're suppose to be at for the desktop view. 

I even used one of the template html codes on the mjml website and sent it to myself with the same results. tested on outlook.com on firefox, safari and chrome.

It seems as if its because the columns have a min-width of the right percentage  (50%) but have a width of 100% which overrides the correct %. when I removed the width="100%" the columns worked.

**Comment by arnaudbreton** [comment]
Hi @lRlevolution, sorry to hear that. Could you please provide us with your MJML code so we can figure out better what's going wrong? Thanks!

**Comment by lRlevolution** [comment]
Look no further than the example templates you have on the site. You can use this one and you will notice the 3 column layout breaks to 100% on a desktop view for outlook https://mjml.io/try-it-live/onepage

**Comment by joaopvilla** [comment]
This is the most frustrating thing to use me. You should rethink the renderer. We spent time creating the structure and testing, stating that it works and when tested in emails they stop working.

<img width="1440" alt="screen shot 2016-04-01 at 09 51 37" src="https://cloud.githubusercontent.com/assets/17101231/14207261/5e1c143e-f7ef-11e5-9486-89411d91488e.png">
<img width="1440" alt="screen shot 2016-04-01 at 09 51 26" src="https://cloud.githubusercontent.com/assets/17101231/14207263/5e80ea44-f7ef-11e5-887c-2de78eab09aa.png">
<img width="1440" alt="screen shot 2016-04-01 at 09 51 21" src="https://cloud.githubusercontent.com/assets/17101231/14207262/5e7e42a8-f7ef-11e5-863c-512bbcb52a54.png">

**Comment by arnaudbreton** [comment]
Hey @joaopvilla @lRlevolution, sorry for the delay in the answers here.

After digging into that issue, it turns out the Outlook Webmail 2016 behaviour won't allow us to support both and desktop and mobile render. For that reason, we decided it would be better for MJML users to go with the mobile rendering, leading to a great render on mobile devices and still decent one on desktop.

About Google Apps, we still haven't figured out what is the exact reason of the issue for some versions of the client. Please watch #24 to get the last updates about this issue.

Beyond these issues, we're aware our online editor can sometimes lead to different results that the final one and we are currently working on alternative solutions. Meanwhile [Litmus](litmus.com) and [Email on Acid](https://www.emailonacid.com/) remain the best solution to use to test the results better.

Apologies for the inconvenience.

**Comment by maximeguerreiro** [comment]
Hey there,
May there be an option if we know our target are using a Desktop (my case: I use mjml to mail my collaborators, not clients)?

Thanks
