### ISSUE TITLE
non responsive images whith columns

### ISSUE THREAD

**Issue by quimpg** [mjmlio/mjml#1723]
When you create a section with multiple columns and the columns contain images the images aren't resposive.

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
	<mj-image  src="http://www.online-image-editor.com//styles/2014/images/example_image.png" />
      </mj-column>
       <mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
	 <mj-image  src="http://www.online-image-editor.com//styles/2014/images/example_image.png" />
      </mj-column>
       <mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
	 <mj-image  src="http://www.online-image-editor.com//styles/2014/images/example_image.png" />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

I expect the images will have 100% width as said in the documentation as default behaviour.

But the size of the image is limited on the td, over the image definiton. 

I got the error on the online editor but also in Gmail for Android and in Chrome with mobile emulation.

**Desktop behaviour (correct)**
![Screenshot from 2019-10-02 11-29-07](https://user-images.githubusercontent.com/2229268/66033833-59c39600-e508-11e9-9446-1bdcc31b6bd4.png)

**Mobile behaviour(bug?)**
![Screenshot from 2019-10-02 11-28-55](https://user-images.githubusercontent.com/2229268/66033834-5a5c2c80-e508-11e9-8598-8cd40198ec73.png)

**Expected mobile behaviour(width:100%)**
![Screenshot from 2019-10-02 11-30-04](https://user-images.githubusercontent.com/2229268/66033831-59c39600-e508-11e9-9af1-8a2c1b4faac2.png)

**Comment by ngarnier** [comment]
You can achieve that by adding the attribute `fluid-on-mobile="true"` on your images (see https://mjml.io/documentation/#mjml-image).

**Comment by gusbemacbe** [comment]
Hello@ngarnier !

But the image is not responsive yet in the computer. I set `mj-body` to `100%`, because my CEO wants the e-mail to be fully responsive in both computer and mobile (already responsive). Check: https://mjml.io/try-it-live/rJ-d58qCB

**Comment by iRyusa** [comment]
mj-body doesn't support full size body. It must be a size in `px`

**Comment by ngarnier** [comment]
That statement is also wrong. You don't need to set `mj-body` to 100% for the email to be fully responsive. It's already handled by MJML with a much better approach (full-width on mobile with a mobile first approach and fixed width on desktop with the fluid-hybrid approach).

**Comment by gusbemacbe** [comment]
@iRyusa and @ngarnier 

> You don't need to set `mj-body` to 100% for the email to be fully responsive. It's already handled by MJML with a much better approach (full-width on mobile with a mobile first approach and fixed width on desktop with the fluid-hybrid approach).

Yes, I removed it, and the image got 100%, but it is limited still to 600px on computer.

https://mjml.io/try-it-live/rJ-d58qCB

> mj-body doesn't support full size body. It must be a size in `px`

**Comment by ngarnier** [comment]
Again, this is the basis of the approach behind MJML. 600px is the optimal width for all email clients (taking into consideration clients that display the email in a panel next to the email list as well) which is why it is the default width. You can change it to another fixed width (for example 700px) but it has to be a fixed width. 

If you don't want that, maybe MJML is not the right tool for you and you'd be better off doing 100%-width tables.

**Comment by gusbemacbe** [comment]
@ngarnier 

> Again, this is the basis of the approach behind MJML. 600px is the optimal width for all email clients (taking into consideration clients that display the email in a panel next to the email list as well) which is why it is the default width. You can change it to another fixed width (for example 700px) but it has to be a fixed width.

I decided to use fixed width, and tested on a responsive design mode, it seemed to be totally responsive and to work. I also sent MJML, and checked on both mobile and desktop, it worked. 

> If you don't want that, maybe MJML is not the right tool for you and you'd be better off doing 100%-width tables.

I know you find my idea wrong. If I want to send e-mail with pure HTML, it will be very hard, because I made several tests and copied the pure HTML to Thudnebird with ThunderHTMLEdit plugin, and the received e-mail did not display well. Or I have to use PHPMailer to send pure HTML, but my CEO and team are not geeks.

I wish I could send pure HTML or HTML exported from MJML, but with modified HTML elements, from MHML by nodemailer.

**Comment by iRyusa** [comment]
Don't use thunderbird, it will alter the HTML in the process. You can use something like https://putsmail.com/ to send test email for free.

**Comment by gusbemacbe** [comment]
Can my CEO and my team use Putsmail to send a HTML exported from MJML or pure HTML to other recipients without test?

**Comment by iRyusa** [comment]
WIthout test ? I don't think i'm following you here, putsmail allow you to test an html into any inbox without any modification on the html from any part (only the client that will open it).

If you wend to send email to a list of people, you'll need to use an ESP for that.
