### ISSUE TITLE
MJML replace css break-all by break-word

### ISSUE THREAD

**Issue by AntoninBeaufort** [mjmlio/mjml#1728]
**Describe the bug**
MJML replace css break-all by break-word, which don't work on Windows 10 Mail and Outlook,
how to force break-all on ms ?

**To Reproduce**
1. Create a file with this MJML code:
 `<mj-style inline="inline">
     .break { -ms-word-break: break-all; }
</mj-style>` 
and 
`class="break"` on very long link
2. Send mail and check it on Outlook, open mail in IE to inspect code and 

**Expected behavior**
The link should not be outside of 600px section.

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML Version [e.g. 4.2.0]
 - MJML tool used [e.g MJML App]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Email Client : Outlook,
 - OS: Windows 10 1908 (build 12026.20108)
 - Browser : IE 11

**Screenshots**
![bug-mjml](https://user-images.githubusercontent.com/33757018/66481270-cc041f80-eaa0-11e9-9cc8-fcc47df319c2.PNG)

**Comment by kmcb777** [comment]
Hi @AntoninBeaufort thanks for reporting this,
There is a default value of `word-break: break-word` already added inline by mjml on this element.
After examination it turns out that the lib we use for inlining css doesn't replace the existing value.
We'll fix that, for now as a workaround, if you add `word-break: break-all !important;` in your inline mj-style, you'll get the result you want (it won't preserve the 'important' tag)
