### ISSUE TITLE
Page break is not working

### ISSUE THREAD

**Issue by Gangotriv** [mjmlio/mjml#1737]
I have a lengthy mail containing details of many person. I want to get the dedicated page per person while printing the mail. So, I want to break the page after every person detail. 

I tried like-

<mj-head>
 <mj-style inline="inline"> 
      @media print {
        .testPrint {
          page-break-after: always;
        }
      }
    </mj-style>
</mj-head>
<mj-body>

    <mj-section>
        <mj-column>
         <mj-spacer height="1px" css-class="testPrint"/>
        </mj-column>
      </mj-section>
</mj-body>

While printing I want a dedicated page for one person information.

**MJML environment (please complete the following information):**
 - OS: [windows]
 - MJML Version [1.6.0]
 - MJML tool used [e.g MJML App]

**Affected email clients (for rendering issues):**
-  Outlook (app and web) and gmail 
 - Browser [e.g. Google Chrome]

**Comment by ngarnier** [comment]
There are two possible explanations, either : 

- your media query is not targeting your element properly and as a consequence it's not properly applied
- the email client is stripping your media query out

It's hard to tell for the first option as you didn't provide any code, but anyway it's very likely due to the second option as most email clients strip styles when printing (there are many references of this on the internet, here's [one example](https://stackoverflow.com/questions/24893628/add-print-styles-to-html-email-for-gmail)).

Either way, we can't do anything about it as we have no control over the email client stripping styles in that specific case.
