### ISSUE TITLE
<mj-raw> in <mj-head> appearing out of order

### ISSUE THREAD

**Issue by didrikg** [mjmlio/mjml#1790]
Hello! 

I'm trying to write an MJML-template for Adobe Campaign and need to define a couple of variables before the CSS `<style>` in the `<head>` of my email.

But while I'm defining the MJML like this:
```
<mjml>
  <mj-head>
    <mj-raw>
      <!-- htmlmin:ignore -->
      <% loadLibrary('cus:contentLibrary.js'); %>
      <!-- htmlmin:ignore -->
    </mj-raw>
    <mj-style>
        // Using variables from cus:contentLibrary.js
    </mj-style>
  </mj-head>
  <mj-body>
    ...
  </mj-body>
</mjml>
```

It spits out HTML like this (with the contents of `<mj-raw>` last in `<head>`):
```
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
  ...
    <style type="text/css">
      // Using variables from cus:contentLibrary.js
    </style>
    <% loadLibrary('cus:contentLibrary.js'); %>
  </head>
  <body>
    ...
  </body>
</html>
```

I would expect it to keep the original order of elements as defined in `<mj-head>`. Is there any way to get around this or would I have to modify the HTML after mjml2html?

**Comment by kmcb777** [comment]
Hi @didrikg the mj-raws in mj-head are indeed all rendered at the end of the head. There is currently no way to change that and it would require quite a lot of changes.
For your use case, since mj-style just renders a `<style>` tag in the head, you could put your style in a `<style>` tag in the mj-raw, like this the order will be left as it is.

**Comment by didrikg** [comment]
Thank you, that is a good enough workaround!
