### ISSUE TITLE
[Question] - How to horizontally inline 2 buttons?

### ISSUE THREAD

**Issue by brunocfalcao** [mjmlio/mjml#1794]
Dear all,

Thank you for this amazing framework, first of all.

I am trying to inline 2 buttons, but can't do it correctly. Somehow I can't apply a section inside a section, to then add 2 columns there.

This is the final result I want to achieve (inside the yellow box):

![image](https://user-images.githubusercontent.com/34269950/72211621-966f3800-34ce-11ea-949d-8b34234b1185.png)

Do you have any suggestions?

Thank you in advance for the help!

**Comment by iRyusa** [comment]
That should be solved in 2 column in it's own section but I think you'll have some content left side too ?

**Comment by brunocfalcao** [comment]
Yes, that's the issue, I already have a section to separate the 2 columns: The totally green column in the left side and the the "welcome to zahper" column. So somehow I would need a nested "section" but that's not possible.

If anyone could help it would worth a million, if not then I might need to make a custom component for this :(

**Comment by iRyusa** [comment]
Technically we could do something to allow to inline component inside a column. But that would imply a lot of limitation.

The best way to do that would be to mimic the mj button within a table with 2 td's.

**Comment by brunocfalcao** [comment]
Thanks! Will close the "issue".

**Comment by dev-marcel** [comment]
I know this issue is closed, but i think the option to do this will greatly contribute to the freedom of making templates. There is a possible solution if we can set the spacing(s) and background image of the mj-navbar-link component. I have made a working concept only the spacings in outlook are broken (Can easily be fixed by adding cellpadding or border spacing in the MSO tag)

![image](https://user-images.githubusercontent.com/11071510/123115825-b1263a00-d440-11eb-8afa-3dcc11902a6c.png)

I hope you all like this idea too, i don't have the time to develop this myself. But it shouldn't be that complex, and I don't see any problems with different email clients myself. Hope someone will do something with it

**Comment by iRyusa** [comment]
There's a lot of "hack" that can exist for that solution. However it's really hard to transition from an idea to markup usage. Let's say we allow to inline element within a column how that would be controled  ? As we're dealing with table it's not that easy to handle padding between element without overflowing the whole column in Outlook ghost tables.

Even if your solution looks to work fine here i'm almost certain that older outlook version might misbehave.


Technically you can nest section+column infinitely https://mjml.io/try-it-live/2mBgU6LRblL and it should render fine everywhere this still need to be tested properly with all tag to see the limiting factor of this (you can't nest background-image, does mj-image render well and not overflow... )

**Comment by renchris** [comment]
How would you have elements side by side without spacing or spaced by the column elements?

TextElementOne TextElementTwo

With the two text elements next to each other in the same line without any padding/spacing from each other
