### ISSUE TITLE
Content in custom components

### ISSUE THREAD

**Issue by arnvvd** [mjmlio/mjml#185]
Hi, 
I would like to create several components which include compaign monitor's tags. So I did this :

```javascript
import _ from 'lodash'
import {
  MJMLColumnElement,
  elements,
  registerElement,
} from 'mjml'
import React, { Component } from 'react'


const {
  text: MjText,
} = elements;


const NAME = 'singleline'


@MJMLColumnElement({
  tagName: 'mj-singleline',
  content: '',
  attributes: {
    'label': ''
    }
})


class Singleline extends Component {

  render() {
    const { mjContent, mjAttribute } = this.props

    if (mjAttribute('label') != '') {
      return (
          <singleline dangerouslySetInnerHTML={{ __html: mjContent() }} label={mjAttribute('label')} />
     )
    }
  }
}

registerElement('singleline', Singleline)
export default Singleline
```

It works, however I don't know how to put my content dynamically in my tags <pre> `<mj-singleline> ...(myContent) </mj-singleline>` </pre> like <pre> `<mj-text> ...(myContent) </mj-text>` </pre>
Can anyone help me ?

**Comment by GuillaumeBadi** [comment]
Hey @arnvvd !

First, you shouldn't make a conditional return. You component has to return something or throw an error.

``` javascript

const label = mjAttribute('label')

if (!label) {
  throw new Error('You have to provide a label to SingleLine')
}

```

then, if your component only contains text, or non-mjml tags, you have to tell the compiler to omit its content: 

``` javascript
registerElement('singleline', Singleline, { endingTag: true })
```

Finally, wrap your rendered html into a div, and set its content to your final result, otherwise, react will throw an error because `singleline` is not defined:

``` javascript

<div dangerouslySetInnerHTML={{
  __html: `<singleline label=${ label }>${ mjContent() }</singleline>`
}}  />
```

Didn't try it, but it should work! Keep me up to date! :+1:

**Comment by arnvvd** [comment]
Thanks a lot @GuillaumeBadi ! It works perfectly, you made my day !

**Comment by arnaudbreton** [comment]
👍 @GuillaumeBadi @arnvvd. I'm closing the issue, feel free to open new ones should you have any questions.
