### ISSUE TITLE
<= character breaks parser

### ISSUE THREAD

**Issue by julius-spudvilas** [mjmlio/mjml#1899]
**Describe the bug**
This issue was described in the previous bug:
https://github.com/mjmlio/mjml/issues/485

I dont think that it was fixed as expected. For example using something like this.

`<mj-raw>var isNewInSale = property.DaysInSale <= 15;</mj-raw>` --- Will break PARSER and output `var isNewInSale = property.DaysInSale <= 15;</mj-raw>`.... anything else from here will not be parsed and we will get mjml code.

`<mj-raw>var isNewInSale = 15 >= property.DaysInSale;</mj-raw>` --- Will work as expected

So seams like < symbol breaking parser while > is working fine

**Comment by iRyusa** [comment]
Well situation now is still way better than #485 but yes, there's still some small cases like that where htmlparser2 thinks that's an opening tag, it's sad because some special tag as `script` support this feature in htmlparser2 (https://github.com/fb55/htmlparser2/issues/72) but as the author said, it's not really an option. 

I don't think there's a proper fix about this one @kmcb777 can we still check if we can do something on this, but I bet the tag is still considered as open for the rest of the file :(

**Comment by kmcb777** [comment]
Hi @julius-spudvilas if you can juste use `<` instead of `<=`, this will work because htmlparser doesn't consider it as a tag.
So if you're comparing integers this workaround should be ok.
Unfortunately i made a few attempts and it turns out that being able to detect on our side that `<=` is not really a tag and make htmlparser ignore it would require to do really hacky things on the parser and i don't think it's safe.

**Comment by julius-spudvilas** [comment]
Well as i mentioned it is always possible to reverse the comparison :)

1<2  is same as 2>1  and secon one always works ;)

**Comment by iRyusa** [comment]
Maybe we should take a look at https://www.npmjs.com/package/parse5  there's a compatibility mode with htmlparser2 don't think we'll be able to try out soon but if someone have time to spare. I guess parse5 might have other issues and maybe no way to handle the line number as we do for linting errors.

I'm closing for now because I think we can't do better for now
