### ISSUE TITLE
mjml-group, mjml-column don't support backgroundUrl

### ISSUE THREAD

**Issue by osdiab** [mjmlio/mjml#1961]
**Is your feature request related to a problem? Please describe.**
They support colors but they don't support images, which is annoying

**Describe the solution you'd like**
They should accept background urls and background size

**Describe alternatives you've considered**
I can't just use mjml-section for my use case because I want to constrain the width of the element with the background image, which section doesn't support

**Comment by iRyusa** [comment]
Well that would be an issue as if we do so we need to support vml for column, need to add some guard to prevent include it into a section with background because vml can't be nested... If you know what you're doing you can still surround the column with VML (mj raw) & support it with css-class with mj-style inline. 

It's far from perfect, but adding background support to column would add a lot of complexity and validation issue.

Background support are quite painful to handle (see https://github.com/mjmlio/mjml/blob/master/packages/mjml-section/src/index.js) so I don't think we'll ever be able to provide it.
