### ISSUE TITLE
Spacing & Buttons side by side in mobile view  *new to HTML coding*

### ISSUE THREAD

**Issue by VIFFxTech** [mjmlio/mjml#1998]
Hi,

I am a novice at coding and is just seeking some help/explanation as to what I can do. 
I have been trying to update our [old festival newsletter templates ](https://archive.viff.org/e-blasts/viff/2019/eblast/09_ALT.html) with better coding standards.

Looking for some guidance and have thrown the project onto this link 
https://mjml.io/try-it-live/r18ct2OZP

Question:
Button elements - How do I get the buttons to sit side by side and have the buttons stay this way in mobile view?
I'm also unsure what the approach would be for the smaller 2 film columns - getting 2 buttons under the copy

I'm just using the MJML app to build this 

Thanks in advance!

**Comment by GarryFlemings** [comment]
@VIFFxTech , about "*new to HTML coding*" and "a novice at coding": Let's just say you're not an _early_ novice! Nice job on your newsletter. It's making good progress.

"just using the MJML app": There are more complicated ways to use MJML, but if this is working for you, great! And it looks like it might work for you completely. I use it a lot, too.

I'd like to help with some of your questions (the simple ones 😁). If I can handle your simple questions, our experts don't spend as much time. If you ask a tough question, you might hear from one of them. And I'll be thankful.

Button elements side-by-side: Consider whether an `mj-table` element would help. Perhaps make it one row and two columns; put one button in each cell. If that doesn't work, let me know and I'll come up with something else.

Back to the beginner status: Everyone here has been where you are and wants to help. We know that without a lot of work on your part, it'll take too much time for us to help you. You've done great work before asking this question and the question is common to MJML. Keep that up and we'll be fine. At the same time, be tolerant if we answer slowly sometimes.

Bonus note today: Don't ignore the red circles with white x's (see lines 5 and 6). Over time, learn the meaning of the words that show when you hover the mouse over those icons. In this case, they say "Element link doesn't exist or isn't registered". You're in the `mj-head` element; each tag there must be for an MJML component. That message is telling you `link` isn't an MJML component (it's HTML). You'll want to find an MJML way to accomplish the same purpose. See whether `mj-raw` can work. The documentation doesn't say it'll work in `mj-head`, but maybe it will.

Strong start. Good luck. 🍀

**Comment by iRyusa** [comment]
You can take a look at mj-group https://mjml.io/documentation/#mj-group if both buttons are on different column it should be enough for you need. If it's in the same column then you'll need to use a table and code button manually.

**Comment by VIFFxTech** [comment]
Thank you both for the guidance/feedback! Sorry for the delay - been juggling other non-coding projects and couldn't follow up as fast I'd like to have (non-profit work = wearing a bunch of hats at the same time). 

Noted with the errors on line 5 + 6 (i kept them there to remind me to add it into the HTML version ha - seems to be fine when I translate it over)

@GarryFlemings  I gave the the `mj-table` method a try! Managed to get two buttons next to each other in one left column but I must be blind and can't figure out the spacing of something that's invisible to me. I tried doing the same thing with the right column with two buttons but it pushes the entire right column down. Like clearly there's not enough space somewhere or I've added too much padding or disregarded some inherent table spacing that I don't know about...that's moving it down.

`mj-group` isn't exactly what I'm looking for as I'd like for the columns to stack and not stay fixed. But thank you for sharing that resource!

Project v2: https://mjml.io/try-it-live/S1zM4wibv 

I'm trying to fiddle around with different button codes I've seen floating around as well but I've ran into I'm stumped as to how to ensure that two buttons side by side within each left + right columns collapse in mobile view in the appropriate column 

This is essentially is what i'm aiming for (disregard styling of the button)

![Newsletter_Wireframes_–_Figma](https://user-images.githubusercontent.com/47042496/89696431-b502a980-d8cc-11ea-9f07-116c80b38fda.png)

**Comment by GarryFlemings** [comment]
> new to HTML coding
> I am a novice at coding

Uh huh ... you fooled me! Back then ... 

> Let's just say you're not an _early_ novice!

Let's say you're not a novice at all! I like your work.

Let's see what we can do to better MJML-ize it! (It's a word _now_!)

Below is your code with modification. I was especially violent with your colors; only for problem-solving. Please forgive.
https://mjml.io/try-it-live/r1DJRJJMv

The warnings on lines 5 and 6 are gone. Kinda cool, eh?! `mj-raw` works in `mj-head`.

The code you wrote is perfect for demonstrating iRyusa's comment,
> if both buttons are on different column it should be enough for you need. If it's in the same column then you'll need to use a table and code button manually.

Let's look at the first half of iRyusa's comment. And at your first (and full-width) section.

1. I closed your full-width section early and added a new (also full-width) section for the buttons.
1. Within the new section, I put an `mj-group` (also full width) for the buttons.
1. Within the `mj-group`, I put two columns, one each for your `mj-button`s. You'll note the buttons remain side-by-side in mobile mode.

Half solved. All credit to iRyusa.

Let's also look at the second half of iRyusa's comment. And at your second (and two-column) section.

Wouldn't it be great if we could put columns in columns? You could have a column for each movie, each of which would have columns for each `mj-button`.

We can't. To iRyusa's point: For these, you need the table approach.

We need to figure out the width problem.

In MJML, we don't have `margin` attributes; those aren't taking space. But some MJML components have default padding.

Your `mj-table` is inside `mj-body`, `mj-section`, and `mj-column`. You'll find in https://mjml.io/documentation that

- `mj-body` doesn't have a `padding` attribute,
- `mj-section`'s `padding` attribute has a default padding of `20px 0`, and
- `mj-column`'s `padding` attribute has a default padding of `n/a`, the same as `0`.

We look next at your `section` `padding`: `padding="0px"`. Many novices miss that. That's not you. Your setting overrides the default. All good.

The default `mj-body` width is 480px. (Not in the documentation. You'll see it in a media query in the HTML; search for "480". You can get wider with `mj-body` `width`; the `480px` stays in the HTML, so the CSS in those media queries don't then have effect.)

`mj-section`s are always 100% width; 480px here.

Where you wanted two columns, you specified `width:50%` on both; you'd expect to get 240px. (If you don't specify `width`, it defaults to exactly that. We're all good.)

The two columns render differently. The two images render differently.

- Images first. You didn't specify `width` (not required); the default is `100%`.

1. The first image looks good. The native image is about 280px wide, so it's downsized to fit right.
1. The second image isn't perfect. The native image is the same about 280px wide. It's rendered differently. I don't notice any difference in attributes. I'm stumped. 😞

- Columns.

1. `mj-image` uses 100% of width by default. I used a green background for each image. The width of the green for the first image (first column) is about 240px, consistent with the 50%. Good.
1. The second image (second column) is about 320px. The columns stack, consistent with the column widths summing to more than the section width of the default 480px.

Could another element within the columns be contributing to this? Sure, but I don't see the problem.

I'd love to take you all the way to the finish line. I'm running out of time today. My next step will be to read the HTML in an attempt to find the problem. I'll try to get to that. If you beat me to it, all the better.

Good luck! 🍀

**Comment by VIFFxTech** [comment]
@GarryFlemings Thank you for the lovely breakdown of logic here and helping me identify the "hidden" default padding and unknowns of certain attributes. ha the coloring is great - really helps break it down a lot better. 

I've just also been trying to identify where in the line of code that is expanding spacing and pushing the columns apart (splitting the "smaller" sized column of the 2 films apart).  

As I'm trying to follow along it does seem like this line of code - the table for the buttons - is the piece of code that pushes the second column (2nd film Escher) down + expands the width of something within the 2nd column (Escher film)
`**<table style="width:230px" background-color="blue" border="0" cellspacing="0" cellpadding="0">**
  <tr style="display: inline-block;">
    <td>
      <table background-color="lime" border="0" cellspacing="5" cellpadding="5">
        <tr>
          <td align="center" style="border-radius: 2px;" bgcolor="white"><a href="https://wwww.viff.org" target="_blank" style="font-size: 14px; font-family: Inter; color: #000000; text-decoration: none; text-decoration: none;border-radius: 20px; padding: 10px 25px; border: 2px solid #000000; display: inline-block;"><b>L B1</b></a>
          </td>
          
          <td align="center"  bgcolor="yellow"><a href="https://wwww.viff.org" target="_blank" style="font-size: 14px; font-family: Inter; color: #000000; text-decoration: none; text-decoration: none; border-radius: 20px; padding: 10px 25px; border: 2px solid #000000; display: inline-block;"><b>L B2</b></a>
          </td>
        </tr>
      </table>         
    </td>
  </tr>
</table>`

I'm quite stumped with this (jumping between MJML + just manual HTML coding).

Hoping to get this working prototype ready for our festival launch in a week or two so if all else fails...
I could just use the default mj button (like in the bottom row of the project example where the button stack on top of each other) but this just seems so do-able!

I'll keep chipping away and try things out. Appreciate your time and support.

**Comment by GarryFlemings** [comment]
Ha! You caught me. I realized a mistake, which led to finding too many more. I deleted the message. Apparently not successfully. We were writing at the same time; you posted first. To quote from the opening of the message I prepared:

> new to HTML coding
> I am a novice at coding

Uh huh ... you fooled me! Back then ... 

> Let's just say you're not an _early_ novice!

Let's say you're not a novice at all! I like your work.
-- end quote --

I know better now that you deserved those words. Found all the good parts in the improvable message. You were tactful enough to avoid mention of the rest. You're no novice at all! Thank you.

I got as far as knowing the problem was in the tables; you have the basis of a full solution. Well done.

This troubleshooting can be time-consuming. Depending on the time you have and the value of your hope for that outer table, don't give up on it. I'm betting there's a way. I won't find it quickly. I'll help, though. Let me know.

About my improvable post:

- Correction: The default "mj-body" width is 600px. [You used it.] You can override it with "mj-body" "width".
- Correction: The default breakpoint (the width below which MJML codes emails for mobile-only rendering) is 480px. That's not in the documentation. It's visible in a couple of media queries in the HTML; search for "480". You can override it with "mj-breakpoint" in the "mj-head" element.
- Unknown to me then, my measured widths were off by a ratio of 480:600 because I wasn't using Try-It-Live at full screen. _Duh! Blush._
- The coincidence that I was measuring 480px width made it far too easy to merge information on the above quite separate concepts. _Sigh._

Me, perfect? No way. Me, concerned about accuracy? Always. And more so after I've erred in writing.

On to happier thoughts.

As part of my problem-solving, I made a copy of the generated HTML and investigated potential for changes there. I only mention it as a problem-solving technique.

You understand HTML. You might get hints from the generated HTML about what MJML is doing ("wrong"). Then, you can tell MJML to do it better. (It's parallel to looking at the object code output when working with a compiled language. And if you have, you have my sympathies! And this is much easier.)

I will recommend (and I'd think you'd say the same): It's safer to find the way to do things through MJML rather than depending on manual adjustment of the HTML every time. I'm thinking of your lines 5 & 6. Back to that soon.

That said, I'll mention some specifics in the improvable message. 

From your "Project update v2: https://mjml.io/try-it-live/r1F5vzyzP": I deleted early sections outside this subject; they remain in your URL. I duplicated sections. I hammered the colors, of course. Please forgive all. All was for problem-solving. Here's a more developed version of my code that you used.
https://mjml.io/try-it-live/Bk4Nm_xGP

The other message described more. I'll avoid including the parts I know you've figured out.

Any line numbers are from your v2 code.

The warnings on lines 5 and 6 are gone. Kinda cool, eh?! "mj-raw" works in "mj-head".

Except, HTML "link" elements need to close. They can self-close ("/>"); they can close with a second tag ("&lt;/link>").

iRyusa said it right
> if both buttons are on different column it [mj-group] should be enough for you need. If it's in the same column then you'll need to use a table and code button manually.

About the first half of his comment and the first movie section of your email, please note my latest code.

1. I closed your full-width section early and added a new (also full-width) section for the buttons.
1. Within the new section, I put an "mj-group" (also full width).
1. Within the "mj-group", I put two columns, one each for your "mj-button"s.

You'll note the buttons remain side-by-side in mobile mode.

Half solved. All credit to iRyusa and his past experience. We all benefit.

If columns could contain groups or columns, we could have a column for each movie, each of which would have columns for each "mj-button".

Alas, we can't do that. So, iRyusa is also right with the second half of his comment: We need the table solution for the second movie section.

Your line 95 and others: In Try-It-Live, the element is in reverse colors. Huh? Oh! On the prior line, an element is not closed.

Your line 116 and others: In Try-It-Live, the element is in reverse colors. Huh? Oh! That's from the prior line. All MJML elements can be self-closing; you used that option with your "/>" at the end. Then you closed it again with a tag. Better with one or the other.

A note about the second and fourth movie sections in my recent code. They have in common that I deleted your mj-table there as an experiment. That made the left column shorter than the right. So, there are stripes below the bottom of the left column and left of the bottom of the right column. The stripes are parent MJML components. The column background is gold. The section background is yellow.

You wouldn't surprise us to ask whether you can make the columns equal width. There've been lots of answers to the question. Most amounted to: You're best to pick background colors for a different purpose than I. (_Bein' a bit proactive ..._)

That might not work if you use a background image on a section (which you can). For such cases, 

If that won't work, I can remember off hand only finding some way to eat up the extra space in the shorter column. There was mention of setting "height" on an "mj-text". Brittle? Dunno, but I'd test carefully.

I something there helps!

A self-serving sales pitch: If we haven't seen you yet on the Slack channel (https://mjml.slack.com), try us! (It's free! Really.) We're a friendly bunch. And people get lots of answers pretty quickly. And the ratio of expert answers to others is really high. Good people. All over the world.

Good luck! 🍀
