### ISSUE TITLE
Image does not scale to device width in Mobile View.

### ISSUE THREAD

**Issue by jaychow99** [mjmlio/mjml#21]
https://mjml.io/try-it-live/kili

I changed http://placehold.it/250x150 to http://placehold.it/600x400. The image does not scale to device width in Mobile View. I expect it to scale to fit without horizontal scroll.

![screen shot 2016-02-07 at 11 29 52 am](https://cloud.githubusercontent.com/assets/16084615/12873875/38b548e0-cd8e-11e5-9b2b-c59b340569c3.png) ![screen shot 2016-02-07 at 11 39 36 am](https://cloud.githubusercontent.com/assets/16084615/12873920/87ce522c-cd8f-11e5-92ef-0080c2f9707f.png)

**Comment by jaychow99** [comment]
I figured it out after reading a closed issue. Add ` width="100%"`
`<mj-image width="100%" src="http://placehold.it/600x400"></mj-image>`

**Comment by michaeldscherr** [comment]
but it would be nice to put the actual width and height of the image, for clients who have their images turned off to start. either the image needs to have a max-width of 100%, or a media query needs to be made for images at a mobile scale to say, "max-width: 100%; height: auto;".

**Comment by iRyusa** [comment]
Hi there !

We've just released the 1.0.3 version of `MJML` that fix the issue in most of clients. However if you're looking at the render in `mobile view` of mjml.io things will still remain broken. It's mostly because the browser will interpret media query, mobile client will ignore them.

Note that using `width: 100%` **isn't supported at all** (#2 is misleading). Image `width` supports only `px` and by default will take `100%` of the column.  

Example: 
![androidgmailapp-vertical-allowed-1366 1](https://cloud.githubusercontent.com/assets/570317/12882711/b9351fb6-ce53-11e5-8d5a-e4fc114ebbc7.png)

**Comment by iRyusa** [comment]
@michaeldscherr does height is really needed ? I can add it easily I guess, but I think how `width` handles it right now is just fine

**Comment by michaeldscherr** [comment]
@iRyusa yes, since some clients have images off by default. sometimes this will cause the layout to break, or the client not being able to show the appropriate ALT tag.

**Comment by iRyusa** [comment]
Ok ! I try to add it for 1.0.4

**Comment by iRyusa** [comment]
@jaychow99 is this ok for you now ? can we close it ?

**Comment by jaychow99** [comment]
Yes, please.Many thanks.Jay-----Original Message-----

**Comment by iRyusa** [comment]
@michaeldscherr height has been added on PR #29 ! thanks for the suggestion

**Comment by rgbjay** [comment]
Hi,

Although this issue is now closed, it does not seem to be fixed. I have had trouble with the responsive images in my email staying at their full size in mobile view. I have tested them in litmus and it still happens, I also tested your Kilamanjaro template in litmus and the image is not responsive there either.

Any help on this would be appreciated.

**Comment by iRyusa** [comment]
@rgbjay Hello, sorry to hear about that but when I put Kilamanjaro in litmus image remain centered and keep full size of column even if I replace with a large ( like 940x150 ) placehold.it image.

Mobile view in the mjml previewer is still bugged, and we're looking to improve it. In Litmus my mail looks fine for me cf https://cloud.githubusercontent.com/assets/570317/12882711/b9351fb6-ce53-11e5-8d5a-e4fc114ebbc7.png

**Comment by rgbjay** [comment]
Yeah, it's looks fine in the gmail app but on iPhone I am seeing the image as non-responsive
![screen shot 2016-02-10 at 14 47 50](https://cloud.githubusercontent.com/assets/11628707/12950492/5ee5a4be-d005-11e5-953c-7c87dad7e06f.png)

**Comment by iRyusa** [comment]
Mhh that's more an iOs specific issue, can you open a new issue for that one ?

I'm checking this right now

**Comment by rgbjay** [comment]
Thanks, I've just created the new issue.
