### ISSUE TITLE
navigation buttons for mj-carousel not displaying in emails

### ISSUE THREAD

**Issue by shinyidol** [mjmlio/mjml#2119]
**Description**
The left/right navigation buttons aren't displaying on mobile or desktop (iOS mail, Gmail Web, Outlook Web). On mobile you can click to change the images, but on desktop web you can't change to other images without proper navigation button. 

**To Reproduce**
1. Create email using mj-carousel. Was able to replicate with sample code.
2. Compile to html and send via email service
3. Open in various clients and attempt to change images

**Expected behavior**
Navigation button to appear to the left and right of the image to allow user to change active image. Pressing thumbnails or navigation button on desktop web should appear and change active image.

**MJML environment:**
 - OS: MacOS 11.1 (BigSur)
 - MJML Version 4.6.2
 - MJML App 3.0.2

**Email sending environment(for rendering issues)**:
 - Sendgrid 

**Affected email clients (for rendering issues):**
 - iOS Mail 14.2, Safari 14.0.2, Chrome 87.0.4280.88
 - OS: MacOC 11.1

**Comment by iRyusa** [comment]
It should work fine on iOS mail (just tested with https://putsmail.com/). If client doesn't support click interaction within email there's nothing we can do about this (like gmail only support hover).

**Comment by shinyidol** [comment]
So I just cut/paste the sample and sent via putsmail and works on iOS.
Hover works on Chrome Desktop on Gmail, but still no navigation buttons and you can't change the image to actually click on associated href.
Navigation Buttons and hover doesn't work on Chrome Desktop on Outlook.com.

If the feature doesn't work, perhaps deprecate it as a feature or at least put a warning.

**Comment by GarryFlemings** [comment]
The difficulty here--for all of us--is the variable and incomplete state of HTML support in email clients (the group you mentioned, iOS, Gmail, Outlook, etc.)

MJML uses an HTML-like markup to create HTML tuned to get the best email performance possible with the current state of clients. Few support anything like the current HTML spec.

If you can do the things you seek to do in HTML across your preferred clients but cannot do them in MJML, then MJML has a problem. Otherwise, sadly, perhaps you'll find email HTML easier by adjusting your expectations for email client responses downward.

Or motivate email client teams to support additional features. You might be a hero here!

**Comment by iRyusa** [comment]
> If the feature doesn't work, perhaps deprecate it as a feature or at least put a warning.

It's just progressive enhancement, if the clients supports some feature they are displayed.
