### ISSUE TITLE
Internal Server error on mjml http server

### ISSUE THREAD

**Issue by landoephan** [mjmlio/mjml#2127]
When using MJML rest api I get the following error since a few hours

```
line 147, in _mjml_render_by_httpserver
    raise RuntimeError('MJML compile error (via MJML HTTP server): {}'.format(msg))
RuntimeError: MJML compile error (via MJML HTTP server): [code=500, request_id=094c4ff2-1b85-4983-ab08-864cce3eb301] An unknown error occurred
```

**Comment by marco-pm** [comment]
Same here, I've been getting random 500 Internal Error responses since yesterday, i.e. some requests go through while others fail with 500 error.
I wrote an email to support@mjml.io but it bounced back - "The email account that you tried to reach does not exist".

**Comment by ngarnier** [comment]
Hi, thanks for reporting, we're investigating.

**Comment by jeffersonrabb** [comment]
Same, seeing this for [Newspack Newsletters](https://github.com/Automattic/newspack-newsletters) too.

**Comment by vaishnavi-accountbox** [comment]
Same here too, I've been getting random 500 Internal Error responses since yesterday, And this is very frequent too.
I wrote an support email to support@mjml.io but it bounced back - "The email account that you tried to reach does not exist".

Here is the sample response {"message":"An unknown error occurred","request_id":"621c088a-d9e1-4f51-be34-96b242a5a030","started_at":"2020-12-29T15:28:46Z"}

**Comment by landoephan** [comment]
problem seem to be solved, luckily I don't use the api in production yet

**Comment by ngarnier** [comment]
The issue should indeed be fixed now.
