### ISSUE TITLE
[Feature Req] Style for phone (like align="left" phone-align="center")

### ISSUE THREAD

**Issue by Hideman85** [mjmlio/mjml#2236]
The feature request is related to style differently on phone and on desktop/tablet.

Taking this sample:
```xml
<mj-section padding="20px 10px">
  <mj-column padding="10px 0" width="100px" vertical-align="middle">
    <mj-image src="${icon}" width="40px" align="center" alt="" padding="0" />
  </mj-column>
  <mj-column width="480px">
    <mj-text font-weight="600" padding="0" padding-bottom="5px">
      ${title}
    </mj-text>
    <mj-text font-size="14px" line-height="16px" padding="0">
      ${desc}
    </mj-text>
  </mj-column>
</mj-section>
```

On desktop/tablet (basically before breakpoint) it is rendering one row with the icon on the left and the text on the right that is align left.
But on mobile the column are stacked making the icon on top with the text below and there the best would be to center the text.

Current workaround would be to assign a class and do everything in a mj-style with a media query.
I'm moving from Fundation for emails (since the design break on some clients included Outlook) but in Fundation you have the possibility to style the component differently for mobile and desktop included phone-hidden class that could be nice to add in mjml too.

I hope you will feel interested by the demand to add this behavior in the framework

**Comment by iRyusa** [comment]
> Current workaround would be to assign a class and do everything in a mj-style with a media query.

You can also do a small helpers class in mj-style and mj-include them for every project, so you can use them locally.

I don't think we really need to add new attributes for such thing where there's no "hack" involved to make it work.

**Comment by Hideman85** [comment]
Yes of course you can do an helper class, then include it in all your project, then create a gist and share your helper function to people, then they would have to include it in their projects too, ...

Is it not the goal of a framework to support that natively? the goal of this feature req? even if this feature does not require any "hack"?

Please just consider in term of design this is really useful (even required) to be able to apply a different style after the breakpoint ;)
PS: most of the code is already there since you generate a media query for the column width :)

**Comment by iRyusa** [comment]
It depends, if you're using an attribute and it doesn't work in X or Y clients because media queries aren't supported you probably blame the framework instead of your code. 

MJML is built as mobile first, so it would mean we'll have to provide a `desktop-align`, ensure it works everywhere and ensure there's no conflict with any other attributes. Some component won't be able to provide this (like mj-image), so it would really be confusing for user to rely on an attribute that would be sometime available.

Same issue if you start to open this to all font related attribute, writing a simple mj-text would require 200 chars for a simple thing that can be resumed in a nice re-useable CSS class  ?
