### ISSUE TITLE
forwarding email, template crashes 

### ISSUE THREAD

**Issue by Cucak** [mjmlio/mjml#2318]
**Describe the bug**
When I receive the email, templates looks good, then from the web I forward it and open my other email account also on the web, template crashes after email is forwarded

**Expected behavior**
Template to look the same after email is forwarded

**Affected email clients (for rendering issues):**
 - Browser [e.g. Google Chrome]

**Comment by GarryFlemings** [comment]
Each time an email client (say, Outlook 365) sends or receives an email, it can change the HTML in the email. Many do, either sending or receiving. The best chance email authors have to get an email to a client in good shape is to send with an Email Service Provider, and then only an ESP that doesn't change the HTML. When we send to clients who change all incoming emails, MJML does lots we don't have to think about to give us a great chance of having the email presentable on arrival.

If you're not sending with an ESP, your email client might be changing the output you get from MJML as it sends. The receiving email client might be changing it both on receipt and again on forwarding. The last email client might be changing it on receipt. That's lots of change.

MJML builds the HTML for all clients in their scope. To write it so that it can forward from and to any email client is not within their scope.

Sorry you have this condition. It's an aspect of email as we know it, not of MJML alone. Good luck.

**Comment by Logesh-cartrabbit** [comment]
I am facing the similar issue in google chrome , I made an email template with MJML received email in inbox as well , but while forwarding the layout breaks .. Is there any solution for this to fix ? @GarryFlemings
