### ISSUE TITLE
Mj-button visible in preview mail but not in test mail

### ISSUE THREAD

**Issue by LindaGOOSEVPN** [mjmlio/mjml#2319]
Hi

I am trying to add a MJML button to my responsive email. The button shows when viewing the preview. However, when i send the test email, the button area remains blank. Does anyone know how to solve this?

![Schermafbeelding 2021-07-01 om 15 13 36](https://user-images.githubusercontent.com/86785231/124130299-e9e89380-da7e-11eb-9a02-c49285b913df.png)

Preview email
![Schermafbeelding 2021-07-01 om 15 12 06](https://user-images.githubusercontent.com/86785231/124130102-b443aa80-da7e-11eb-9d52-9c3c8f568382.png)

Test email
<img width="550" alt="Schermafbeelding 2021-07-01 om 15 12 32" src="https://user-images.githubusercontent.com/86785231/124130160-c3c2f380-da7e-11eb-9894-f399205cc1af.png">

Thanks!

**Comment by GarryFlemings** [comment]
We want to help. Perhaps we need more information.

Covering basics first:

* Did you send your email through an ESP or with your email client (like, Gmail)? Last I heard, www.putsmail.com still had a free service to send test emails without changing the HTML. (Don't check the option to inline CSS.) Litmus offers the service; they're among the best-known ESPs. They ask you to create a free web account to use the service.

* We may need to see more of your code. Might you include some code for us? Try-it-Live (https://mjml.io/try-it-live) is great and free! It doesn't need to be all your code. A small piece of the code that demonstrates the problem is great, too.

More later!

**Comment by LindaGOOSEVPN** [comment]
I managed to solve the problem. There were some open tags in the code. Thanks anyways
