### ISSUE TITLE
MJML Column's "break-word" should be configurable

### ISSUE THREAD

**Issue by chadfurman** [mjmlio/mjml#2363]
**Is your feature request related to a problem? Please describe.**

The issue is that there is unexpected breakage of the words in my navigation bar:
![Screen Shot 2021-09-20 at 8 48 55 AM](https://user-images.githubusercontent.com/635170/134004906-99ea9a60-deae-4717-bb70-7aae26882df2.png)

It should look like this:
![Screen Shot 2021-09-20 at 8 49 15 AM](https://user-images.githubusercontent.com/635170/134004951-199ab389-e30d-468e-9ed3-42551e9a6536.png)

**Describe the solution you'd like**
Ideally I'd have a convenient way of just disabling this feature with a prop on the mj-column block so that this can be changed here: https://github.com/mjmlio/mjml/blob/master/packages/mjml-column/src/index.js#L275 

**Describe alternatives you've considered**
For now, I think I can just force override the style.  There's various ways I can make this happen.

**Comment by iRyusa** [comment]
Well it's not an attribute because the default behavior suits for most email : It ensure the body's width won't overflow and produce different results on clients.

There's already multiples way to override it (mj-style inline, css-class, inline style).

If it's really necessary to have an attribute for this, feel free to open a PR it won't really cost much to add an extra attribute

**Comment by chadfurman** [comment]
My product manager agrees with you that this default behavior is actually the preferred behavior.  Also, this was trivially easy to override with `headStyles` so I'm going to close this.
