### ISSUE TITLE
Right column set in % ignoring left column set fixed width on some breakpoint

### ISSUE THREAD

**Issue by Scorpovi4** [mjmlio/mjml#2367]
**Describe the bug**
Right column set in % ignoring left column set fixed width on some breakpoint, not sure is that bug or correct behaviour, but how to fix it to let left column be static and only right column change own width in responsive mode?

https://mjml.io/try-it-live/3MGgKaxc_Mh

**Expected behavior**
Left column set static with word wrap only right column

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version: VS code extention version
 - MJML tool used: VS code extention

**Comment by iRyusa** [comment]
There's multiple errors in your MJML

- Don't use mj-raw like this it would produce invalid HTML at the end, use mj-text if you need to use some standard HTML
- Section can't have more than 100% of content inside it or it will misrender on Outlook

https://mjml.io/try-it-live/MWJInbRkBct You should use mj-image instead of raw html img tag as it won't handle overflow properly.
