### ISSUE TITLE
Do you have integration tests

### ISSUE THREAD

**Issue by SebastianStehle** [mjmlio/mjml#2451]
Hello,

we are working on a port from mjml to C#. One of the reasons is that the performance of the Node implementation could be better. 

We are wondering how you test mjml. We found only a few tests in the mjml codebase and no integration tests in the github CI. Do you use mjml in production at mailjet and do you have tests to render the html output in a real browser? I have seen that there are a few commercial tools for that in the market.

If you have tests: Would you make them available or would you even include a port to your pipeline?

**Comment by iRyusa** [comment]
We had a styleguide.mjml at some point with every components that we had to run manually in EmailOnAcid to ensure nothing broke visually on clients after a release. 
But it needed to be done manually as there's too many clients to test and no automated tool for that.

There not much test in the project due to limited resources we had when we've moved from React to this current state of MJML4.

**Comment by SebastianStehle** [comment]
It is up to you of course. It could just help us to get visibility and perhaps help you to show how important mjml is.

 We could make it very clear in the repository description. that it is a community contribution. I was also not aware that there is a rust port and I think that personal accounts are not the best place for a repository.
