### ISSUE TITLE
[Question] <mj-image> width lost it's float part when it's placed in <mj-column width="n%"> 

### ISSUE THREAD

**Issue by xlnhaha** [mjmlio/mjml#2566]
**Describe the bug**
mj-image width lost it's float part when it's placed in mj-column width="n%"
**To Reproduce**
mjml code:

`<mjml>
  <mj-body>
    <mj-section>
      <mj-column padding="0" width="20.23%">
        <mj-image padding="0" src=""></mj-image>
      </mj-column>
      <mj-column padding="0" width="30.32%">
        <mj-image padding="0" src=""></mj-image>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

when the image's width is default value, it's like it will render as 100%, but the final value lost its float part.(121.38 -> 121).
This could cause some small blank rendered like this:
![image](https://user-images.githubusercontent.com/34709921/198822321-9737054e-8326-4492-a415-83f0aaaf4116.png)

if the width value is right, it will render like this:
![image](https://user-images.githubusercontent.com/34709921/198822317-5d1b0d5f-494e-4e95-83e4-e402a9a0c2df.png)

is this a bug? Is there any suggestion to avoid the extra blank?
Thank you!

**Comment by iRyusa** [comment]
I don't know if it's really a bug or somehting, but you should avoid float pixel value with % as it could lead to potential whitelines issue in some browsers. Not sure if this is something we could tackle as we have can't round effectively the pixel value (this could lead to either +1 or -1 pixel in the outlook ghost table).

**Comment by xlnhaha** [comment]
Hi iRyusa, thanks for your reply and i change my column width to a int  with %, it rendered like this
![image](https://user-images.githubusercontent.com/34709921/199135513-d6873a4b-fbd3-4277-8682-f635491e6327.png)
i think 23%*(550px) = 126.5px  and image's width should be 126.5px too, but in fact, it lost it's float part and rendered as 126px. i also read the code of mjml-browser, it likely handled the value with parseInt, is this necesssary? can it use parseFloat?

**Comment by iRyusa** [comment]
The final output of a % column should be an int pixel value to ensure this case won’t exist.On 1 Nov 2022, at 01:54, xlnhaha ***@***.***> wrote:﻿
Hi iRyusa, thanks for your reply and i change my column width to a int  with %, it rendered like this

i think 23%*(550px) = 126.5px  and image's width should be 126.5px too, but in fact, it lost it's float part and rendered as 126px. i also read the code of mjml-browser, it likely handled the value with parseInt, is this necesssary? can it use parseFloat?

**Comment by xlnhaha** [comment]
> The final output of a % column should be an int pixel value to ensure this case won’t exist.On 1 Nov 2022, at 01:54, xlnhaha ***@***.***> wrote:﻿ Hi iRyusa, thanks for your reply and i change my column width to a int with %, it rendered like this i think 23%*(550px) = 126.5px and image's width should be 126.5px too, but in fact, it lost it's float part and rendered as 126px. i also read the code of mjml-browser, it likely handled the value with parseInt, is this necesssary? can it use parseFloat? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

I see, thank you very much, and i have another question, is all mjml pixel value should be int for outlook reason？

**Comment by iRyusa** [comment]
Not only, even in browser float pixel tend to do weird stuffOn 1 Nov 2022, at 09:01, xlnhaha ***@***.***> wrote:﻿

The final output of a % column should be an int pixel value to ensure this case won’t exist.On 1 Nov 2022, at 01:54, xlnhaha @.> wrote:﻿ Hi iRyusa, thanks for your reply and i change my column width to a int with %, it rendered like this i think 23%(550px) = 126.5px and image's width should be 126.5px too, but in fact, it lost it's float part and rendered as 126px. i also read the code of mjml-browser, it likely handled the value with parseInt, is this necesssary? can it use parseFloat? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.*>

I see, thank you very much, and i have another question, is all mjml pixel value should be int for outlook reason？
