### ISSUE TITLE
Styles unpredictably removed by gmail from some elements in minified HTML

### ISSUE THREAD

**Issue by NoRePercussions** [mjmlio/mjml#2710]
**Describe the bug**
A single inline style is reliably removed from a text element in my email when processed by Gmail. This issue is not present on Apple Mail. Other elements with identical style tags do not have their styles removed.

I can reliably reproduce this bug with one email. Significant changes result in the correct processing behavior, making it difficult to reproduce.

*The issue is resolved by adding spaces after semicolons in the inline style.*

The element (note that other elements with identical styles work fine!)
```
<div style="font-family:roboto;font-size:13px;line-height:1;text-align:left;color:#313539;">
```

**To Reproduce**
I cannot statically reproduce this. Even prompting changes to the email header seems like it can disrupt it, but it otherwise has proven to be deterministic.

**Expected behavior**
Style tags should not be arbitrarily removed.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.12.0
 - MJML App

**Email sending environment(for rendering issues)**:
 - Rendered further with Jinja
 - Sent with [Sendgrid](https://sendgrid.com/)
 - Viewed in Gmail (buggy) / Apple Mail (correct)

**Affected email clients (for rendering issues):**
 - Gmail, both gmail.com on chromium and iOS app

**Additional context**
By inspecting the original email in gmail, it is clear that the HTML is getting through fine, and gmail's renderer removes the styles.

I understand that this is a problem in gmail's rendering, but it affects MJML-exported HTML.

It appears to me that adding spaces after semicolons in styles fixes the issue (and this has been [reported by others before](https://stackoverflow.com/a/38041282/11789440)).

**Comment by iRyusa** [comment]
Can you try with putsmail.com to be sure it behave the same with it ? It’s weird, the only bug that I’m aware of is when you have a invalid css in style attribute or block, gmail strips it completely.On 14 Jul 2023, at 15:24, Tucker Shea ***@***.***> wrote:﻿
Describe the bug
A single inline style is reliably removed from a text element in my email when processed by Gmail. This issue is not present on Apple Mail. Other elements with identical style tags do not have their styles removed.
I can reliably reproduce this bug with one email. Significant changes result in the correct processing behavior, making it difficult to reproduce.
The issue is resolved by adding spaces after semicolons in the inline style.
The element (note that other elements with identical styles work fine!)
<div style="font-family:roboto;font-size:13px;line-height:1;text-align:left;color:#313539;">

To Reproduce
I cannot statically reproduce this. Even prompting changes to the email header seems like it can disrupt it, but it otherwise has proven to be deterministic.
Expected behavior
Style tags should not be arbitrarily removed.
MJML environment (please complete the following information):

OS: MacOS
MJML Version 4.12.0
MJML App

Email sending environment(for rendering issues):

Rendered further with Jinja
Sent with Sendgrid
Viewed in Gmail (buggy) / Apple Mail (correct)

Affected email clients (for rendering issues):

Gmail, both gmail.com on chromium and iOS app

Additional context
By inspecting the original email in gmail, it is clear that the HTML is getting through fine, and gmail's renderer removes the styles.
I understand that this is a problem in gmail's rendering, but it affects MJML-exported HTML.
It appears to me that adding spaces after semicolons in styles fixes the issue (and this has been reported by others before).

**Comment by NoRePercussions** [comment]
It works fine from putsmail. Though I noticed that it does change the raw email content by adding more line breaks.

**Comment by iRyusa** [comment]
Then most likely sendgrid alter the output HTML and there’s nothing we can do on our end.On 14 Jul 2023, at 15:58, Tucker Shea ***@***.***> wrote:﻿
It works fine from putsmail. Though I noticed that it does change the raw email content by adding more line breaks.

**Comment by NoRePercussions** [comment]
The html is arriving intact, according to the "original message" in gmail.

I agree that this is probably not the right place to look for a fix; I raised an issue in case it needs to be mitigated and for a record. I will just be using the non-minified html or hand-edit issues for now.
