### ISSUE TITLE
documentation on Custom Social Element snippet is missing

### ISSUE THREAD

**Issue by Martzyx** [mjmlio/mjml#2736]
**Describe the bug**
In the https://documentation.mjml.io/#mj-social section, in the "Custom Social Element" section, it says "You can add any unsupported network like this:" And no snippet is appended.
I found the snippet in the [.md file, lines 136-140](https://github.com/mjmlio/mjml/blob/f23addd342eec9e00bd5c02c437d2be178435c49/packages/mjml-social/README.md?plain=1#L136-L140), but it doesn't render the snippet on the docs website.

**To Reproduce**
1. Go to https://documentation.mjml.io/#mj-social
2. Scroll down to "Custom Social Element"
3. See lack of snippet after "You can add any unsupported network like this:"

**Expected behavior**
I expected this snippet to render / be there:
```
<mj-social-element href="url" background-color="#FF00FF" src="path-to-your-icon">
  Optional label
</mj-social-element>
```

**Screenshots**
![Screenshot](https://github.com/mjmlio/mjml/assets/114746510/8b4510b6-9bc3-4063-afbf-150f34245812)

**Comment by iRyusa** [comment]
The code is on the right side like every other code snippets. Slate make this hard to alignOn 28 Aug 2023, at 13:30, Martz ***@***.***> wrote:﻿
Describe the bug
In the https://documentation.mjml.io/#mj-social section, in the "Custom Social Element" section, it says "You can add any unsupported network like this:" And no snippet is appended.
I found the snippet in the .md file, lines 136-140, but it doesn't render the snippet on the docs website.
To Reproduce
Steps to reproduce the behavior:

Go to https://documentation.mjml.io/#mj-social
Scroll down to "Custom Social Element"
See lack of snippet after "You can add any unsupported network like this:"

Expected behavior
I expected this snippet to render / be there:
<mj-social-element href="url" background-color="#FF00FF" src="path-to-your-icon">
  Optional label
</mj-social-element>

Screenshots
