### ISSUE TITLE
Mj-column showing mobile version

### ISSUE THREAD

**Issue by ariefsn** [mjmlio/mjml#2774]
**Describe the bug**
Trying with simple mj-column, working fine on other clients. But in outlook windows app, seems it's always showing as mobile version.

**To Reproduce**
`<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        
        <mj-text>
        	first column
        </mj-text>
      </mj-column>
      <mj-column>
        
        <mj-text>
        	second column
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

1. Create a file with this MJML code: [https://mjml.io/try-it-live/upqN9sTVVg](https://mjml.io/try-it-live/upqN9sTVVg)

2. Render it to HTML by doing 'mjml ./input.html -o output.html'
3. 
![image](https://github.com/mjmlio/mjml/assets/33569737/fb054481-eecb-4bba-8661-e58074c18dd9)

**Expected behavior**
Can see 2 columns horizontally. Like other clients.
![image](https://github.com/mjmlio/mjml/assets/33569737/cf29ec63-b0d1-4025-9489-37a6edd43ac0)

**MJML environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - MJML Version: 4.14.1
 - MJML tool used: CLI

**Affected email clients (for rendering issues):**
 - Email Client: Outlook 365
 - OS: Windows 10 Pro

Thanks

**Comment by iRyusa** [comment]
Try to send the email via https://putsmail.com/ you're altering the output
HTML in some way.

**Comment by ariefsn** [comment]
Thank you @iRyusa you're correct.
The backend using go embed feature here [https://pkg.go.dev/embed](https://pkg.go.dev/embed)
Seems its altering the HTML.
The solution is read the HTML directly instead of embedding.
Case closed, not an issue from MJML.

**Comment by iRyusa** [comment]
Try to send email via https://putsmail.com/

**Comment by brfignoni** [comment]
@iRyusa **Happy update**: 

thanks for the quick reply. I tried that before. It seems the issue is with the [visual studio code plugin](https://github.com/attilabuti/vscode-mjml). I am using the MJML: Export HTML function. On my local machine it looks fine, but as I said, after sending the output HTML, the cols look a little broken on gmail. 

After installing mjml globally with npm, and using it for the output, and sending with litmus, it looks just fine.
My guess is that there is something wrong with the visual studio code plugin.
