### ISSUE TITLE
Text padding problem

### ISSUE THREAD

**Issue by mdrick** [mjmlio/mjml#279]
Hi all,

I have the impression that the right and left padding are broken for the <mj-text> tag.

**Comment by ngarnier** [comment]
Hey @mdrick, thanks for opening this issue. Could you please provide more information, such as: 
- The version of MJML you’re using
- The MJML code you used
- The name and version of the email client(s) on which a bug is encountered (ideally with screenshots)
- What you would expect instead of what's happening

Cheers!

**Comment by iRyusa** [comment]
Closing this one, feel free to reopen with more informations
