### ISSUE TITLE
Add mjml-python to community page

### ISSUE THREAD

**Issue by mgd020** [mjmlio/mjml#2815]
Add [mjml-python](https://github.com/mgd020/mjml-python) to [community page](https://mjml.io/community)

**Comment by iRyusa** [comment]
Can you open a PR about this ? In the tooling section please

**Comment by iRyusa** [comment]
My bad, I meant this one : https://github.com/mjmlio/mjml/blob/master/doc/ports.mdOn 17 Mar 2024, at 03:24, mgd020 ***@***.***> wrote:﻿
Hi @iRyusa,
Do you mean this (source) section? I'm not sure how appropriate it would be to add the Python library there. I do not see any other libraries listed there.
I originally suggested the community page due to there being other libraries analogous to mjml-python, so to me it made sense to add it along side.
Keen to hear your thoughts.
