### ISSUE TITLE
Column and text not rendering

### ISSUE THREAD

**Issue by hugomassing** [mjmlio/mjml#282]
Hello MJML team, I've been using mjml for some time now, and it's a fantastic product! 

I have a problem with my mjml code, I don't understand why some parts of my html wont render. 

Here is the file : 
https://mjml.io/try-it-live/a7dbc46bbad2f763b1f7b3c14295e00d

There is 1 column of the "News" section not rendering, and an image + a section under the "Kaytranada" part. I tried to delete every section 1 by 1 to see the bug, but I couldn't find it and the rendering engine is not giving me any errors.  If you can either give me an insight, or maybe it's a bug. 

Thanks in advance!  

Hugo

**Comment by dalefish** [comment]
Hi Hugo,

On first glance I can see you've got unclosed <mj-image> tags, these have to be closed with </mj-image>

<mj-image src="top-image.jpg" width="640" height="auto" padding="0" href="https://www.google.co.uk"></mj-image>

Not sure why but it's tripped me up before too.

**Comment by ngarnier** [comment]
Hey @hugomassing, thanks for your feedback and opening this issue.

As @dalefish pointed out, the issue is related to the image tags. Actually, you just discovered an issue that happens when you mix `<mj-image></mj-image>` with `<mj-image />`, we'll look into it.

Until then, choosing either the closing or the self-closing tag should fix your issue. Let us know if it works for you!

**Comment by hugomassing** [comment]
Yes, thanks for your help, I figured it out!
