### ISSUE TITLE
Helper UrlEncode does not return the expected result

### ISSUE THREAD

**Issue by braiscp** [mjmlio/mjml#2863]
**Describe the bug**
I have been doing different tests when sending a parameter in a url with the value of an email and it seems that the only character it encodes is blank space when the expected result is that it encodes all special characters such as + or @.

**To Reproduce**
1. Create a MJML file 
2. Create a string variable initialized to a string with several special characters. For example: "one+two@gmail com"
3. Create a mj-text tag. Inside print the value of the variable and the result after applying the UrlEncode function

**Expected behavior**
Encoded string result: "one+two@gmail%20com"
Encoded string expected: "one%2Btwo%40gmail%20com"

**MJML environment:**
 - OS: Ubuntu & MacOS
 - MJML Version 4.15.3

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [Mailjet](www.mailjet.com/)

**Affected email clients (for rendering issues):**
 - Email Client: Gmail 
 - OS: Ubuntu & MacOs
 - Browser: Google Chrome

**Comment by iRyusa** [comment]
This is not Mailjet support here. Please open a ticket on their website.On 23 May 2024, at 19:19, braiscp ***@***.***> wrote:﻿
Describe the bug
I have been doing different tests when sending a parameter in a url with the value of an email and it seems that the only character it encodes is blank space when the expected result is that it encodes all special characters such as + or @.
To Reproduce
Steps to reproduce the behavior:

Create a MJML file
Create a string variable initialized to a string with several special characters. For example: ***@***.*** com"
Create a mj-text tag. Inside print the value of the variable and the result after applying the UrlEncode function

Expected behavior
Encoded string result: ***@***.***%20com"
Encoded string expected: "one%2Btwo%40gmail%20com"
MJML environment:

OS: Ubuntu & MacOS
MJML Version 4.15.3

Email sending environment(for rendering issues):

Platform used to send the email Mailjet

Affected email clients (for rendering issues):

Email Client: Gmail
OS: Ubuntu & MacOs
Browser: Google Chrome

**Comment by braiscp** [comment]
Good morning @iRyusa 

Sorry to bother you again Maxime, but what kind of support is provided in this repository? Because I thought that what I need I was requesting well through this means. I have opened a support ticket as you told me but they told me that they do not provide support for the developed code. Can you review what I mentioned in the issue again and if you think this is not the right means of communication, tell me where and who I should contact? What is really happening is that a function of the documentation is not doing its job well.

**Comment by iRyusa** [comment]
Hi,
I'm just providing support for MJML not Templating language from Mailjet and i'm not affiliated with them.
