### ISSUE TITLE
Inline external fonts

### ISSUE THREAD

**Issue by felixmosh** [mjmlio/mjml#2890]
**Is your feature request related to a problem? Please describe.**
instead of generating a link tag [here](https://github.com/mjmlio/mjml/blob/f70f7d80ccfd91b88931ab9a055c6e4a54ac5bcc/packages/mjml-core/src/helpers/fonts.js#L21), I see that some libs like `email-template` inlines the resulting css (using `juice`).

**Describe the solution you'd like**
Instead of generating a link tag, maybe it is better to make a call to the link, and generate the `style` tag with the result.

**Comment by iRyusa** [comment]
It won’t really help with the support https://www.caniemail.com/features/css-at-font-face/ anyway so it’s not really something we’ll considerOn 11 Aug 2024, at 11:34, Felix Mosheev ***@***.***> wrote:﻿
Is your feature request related to a problem? Please describe.
instead of generating a link tag here, I see that some libs like email-template inlines the resulting css (using juice).
Describe the solution you'd like
Instead of generating a link tag, maybe it is better to make a call to the link, and generate the style tag with the result.
