### ISSUE TITLE
mj-raw component breaks html in multi column layout

### ISSUE THREAD

**Issue by malikov917** [mjmlio/mjml#2898]
**Describe the bug**
Using mj-raw in multiple column layout breaks layout.

**To Reproduce**
1. Open [https://mjml.io/try-it-live/](https://mjml.io/try-it-live/)
2. Add code snippet
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-raw>
          <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;">
            <tbody>
              <tr>
                <td style="width:548px;"> <img src="https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_default_2x_r5.png" /> </td>
              </tr>
            </tbody>
          </table>
        </mj-raw>
      </mj-column>
      <mj-column>
        <mj-raw>
          <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;">
            <tbody>
              <tr>
                <td style="width:548px;"> <img src="https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_default_2x_r5.png" /> </td>
              </tr>
            </tbody>
          </table>
        </mj-raw>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
It is possible to create a layout with columns and raw html nested in.

**MJML environment:**
 - https://mjml.io/try-it-live/ **v4.9.3**

**Screenshots**
Browser kicks second column out from parent `mj-section`:
![image](https://github.com/user-attachments/assets/d291c16c-b971-4ca2-afa4-3739c2784fc3)
Two images are not in the same row:
![image](https://github.com/user-attachments/assets/a38a879f-26b8-42a1-a24d-c411ae2aebf9)

**Additional context**
Wrapping up `<mj-raw>` with another `<mj-section>` somehow fixes the issue
Workaround which worked:
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-section>
          <mj-raw>
            <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;">
              <tbody>
                <tr>
                  <td style="width:548px;"> <img src="https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_default_2x_r5.png" /> </td>
                </tr>
              </tbody>
            </table>
          </mj-raw>
        </mj-section>
      </mj-column>
      <mj-column>
        <mj-section>
          <mj-raw>
            <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;">
              <tbody>
                <tr>
                  <td style="width:548px;"> <img src="https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_default_2x_r5.png" /> </td>
                </tr>
              </tbody>
            </table>
          </mj-raw>
        </mj-section>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
**Screenshot of working example:**
![image](https://github.com/user-attachments/assets/506d7082-fe81-4c63-a72f-7a1ba2111a33)

**Comment by iRyusa** [comment]
You don’t produce valid html with your mj raw here so the browser will misinterpret it. Just use a regular mj-text here instead or wrap your table in a tr + tdOn 6 Sep 2024, at 18:12, Kanstantsin Malikau ***@***.***> wrote:﻿
Describe the bug
Using mj-raw in multiple column layout breaks layout.
To Reproduce
Steps to reproduce the behavior:

Open https://mjml.io/try-it-live/
Add code snippet
`

  
    
      
        
          
            
              
                  
              
            
          
        
      
      
        
          
            
              
                  
              
            
          
        
      
    
  
`
Expected behavior
It is possible to create a layout with columns and raw html nested in.
MJML environment (please complete the following information):

https://mjml.io/try-it-live/ v4.9.3

Screenshots
Browser puts second column out from parent mj-section:
image.png (view on web)
image.png (view on web)
Additional context
Wrapping up  with another  somehow fixes the issue
Workaround which worked:
<mjml> <mj-body> <mj-section> <mj-column> <mj-section> <mj-raw> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"> <tbody> <tr> <td style="width:548px;"> <img src="https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_default_2x_r5.png" /> </td> </tr> </tbody> </table> </mj-raw> </mj-section> </mj-column> <mj-column> <mj-section> <mj-raw> <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;"> <tbody> <tr> <td style="width:548px;"> <img src="https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_default_2x_r5.png" /> </td> </tr> </tbody> </table> </mj-raw> </mj-section> </mj-column> </mj-section> </mj-body> </mjml>

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by malikov917** [comment]
hi @iRyusa ! thanks for the reply. You are absolutely right, mj-text did the trick, thanks a lot!

But what do you think about the behavior I've described above? I was suprised seeing a block of generated html to be out of my component :) 

Also I, as a user, would expect it working with mj-raw and wouldn't think about mj-text honestly. Maybe it makes sense to udpate documentation and add a link from mj-raw to mj-text in case someone wants to achieve similar behavior?

**Comment by iRyusa** [comment]
It's not our fault that Chrome will "push" your HTML out of a table because it's an invalid DOM structure. If you just check  the source HTML you'll see that everything is placed as expected.
