### ISSUE TITLE
Problem Outlook.live.com

### ISSUE THREAD

**Issue by Yentia** [mjmlio/mjml#314]
Hi,

My email is always in responsive format in outlook.live.com. ( last version of website )
any idea to resolve this problem ?

for example  : 
width this code : 

```
<mjml>
<mj-body>

<mj-container font-family="Open Sans">

<mj-section>
	
	<mj-column background-color="green">
		<mj-text>Bloc 1</mj-text>
	</mj-column>

	<mj-column background-color="blue">
		<mj-text>Bloc 2</mj-text>
	</mj-column>

	<mj-column background-color="red">
		<mj-text>Bloc 3</mj-text>
	</mj-column>

</mj-section>

</mj-container>

</mj-body>
</mjml>
```

correct render in outlook 2013 software
![outlook_2013_software](https://cloud.githubusercontent.com/assets/8813073/16296426/82e40ac8-392c-11e6-9721-774d0b0172f5.PNG)

but in outlook.com ( web) 
![outlook com web](https://cloud.githubusercontent.com/assets/8813073/16296442/9835210a-392c-11e6-9e40-1ddf2920ca30.PNG)

thanks

**Comment by ngarnier** [comment]
Hi @Yentia, thanks for opening this issue! The problem has been reported [here](https://github.com/mjmlio/mjml/issues/40) so I'll close the issue to keep things over there. 

Unfortunately, the only options we have are: 
- always display the mobile version (including on desktop)
- always display the desktop version (including on mobile) 

Obviously, mobile on desktop is the most readable approach so that's the one we picked.
