### ISSUE TITLE
Vertical Scrollbars in Yahoo!/IE

### ISSUE THREAD

**Issue by f4f343w4tcfwv4tz5tb5** [mjmlio/mjml#320]
Adding padding="0" to an <mj-section> creates vertical scrolling in Yahoo!/IE combination:

Simple MJML like so:

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section padding="0">
        <mj-column>

          <mj-text>
            Hello world
          </mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

Screenshot: http://screencast.com/t/wyGrVE8vrP

**Comment by zrb0529** [comment]
I'm seeing good results by adding `overflow: hidden !important;` to

```
table, td {
    border-collapse: collapse;
    mso-table-lspace: 0pt;
    mso-table-rspace: 0pt;
}
```

in the code that MJML generates.

**Comment by iRyusa** [comment]
Is this still a thing?

**Comment by zrb0529** [comment]
yes :(

**Comment by edgahan** [comment]
Still a thing, above fix worked for me.

**Comment by iRyusa** [comment]
Reopening the issue and reverting the fix, adding the overflow hidden break some borders in some case

**Comment by cppchriscpp** [comment]
Still running into this issue on 3.3.5, unfortunately. The workaround above caused a ton of other problems for me.

I had a little luck adding this mj-style tag to my template: 
```
<mj-style>
            @media screen yahoo {
                * {
                    overflow: visible!important
                }
                .y-overflow-hidden {
                    overflow: hidden!important
                }
            }

</mj-style>
```

No idea if this will work for all use cases - I based it off this forum post: https://www.emailonacid.com/forum/viewthread/824/P10/#1915

Someone did a little digging into where this problem came from here: https://mosaico.io/email-client-tricks/about-unexpected-scrollbars-in-yahoo-webmail/

I am not currently working towards a PR, but hopefully this helps someone with the same issue!

**Comment by iRyusa** [comment]
Only issue with this fix : it will hide some borders in some cases :/ 
That's why we've reverted the fix yet

**Comment by iRyusa** [comment]
Seems that it's no longer an issue, closing it
