### ISSUE TITLE
Fix package.json to enable installing a specific version

### ISSUE THREAD

**Issue by liminspace** [mjmlio/mjml#349]
Hi!

I install some version MJML. For example:

    # npm install mjml@2.1

Then I check version:

    # node_modules/.bin/mjml --version
    2.3.1

I think it is because mjml-cli 2.3.1 was installed.
I want run my tests for each version of MJML -- 2.0, 2.1, 2.2, 2.3 etc.
How I can easy install some version MJML with right dependencies? Is it possible in JavaScript world?

**Comment by ngarnier** [comment]
Hey @liminspace, to install a specific version of mjml, you can indeed to: 
`npm install mjml@2.1.0`

I think the issue here is that you didn't specify the patch version. Let me know if it helped.

**Comment by liminspace** [comment]
`npm install mjml@2.1.0` is not good for me because if I install 2.1 then I want latest 2.1.x version. It is not good way if I will often check minor(patch) version and update file that run tests.

And `npm install mjml@2.1.0` is not work for me. It installs mjml 2.1.0 but other dependencies have latest version.

**Comment by ngarnier** [comment]
Sorry I had misunderstood your issue initially, indeed if you want the latest patch version for a given minor version, `npm install mjml@2.1` should work. 

Definitely a npm issue here. I think here is what happens with npm: `mjml-core` is a dependency of `mjml`, because we're talking about minor versions, `mjml-core@2.3.1` is supposed to be retro-compatible, better and not break anything compared to `mjml-core@2.1.1`, so npm gets the latest minor version for the given major version you asked. The only option I see (I know it's not ideal though) is explicitly specifying the dependencies you want in your package.json.

**Comment by ngarnier** [comment]
Hey @liminspace, after checking again, we could enable you to install a specific version if we specified dependencies with a tilde (`~`) instead of  a caret (`^`) in our package.json.

The package.json was not designed this way until now so you won't be able to download specific versions under 2.3.1 but we'll make sure to do it this way starting from now so you can do it for the future versions. Sorry for the trouble and thanks for reporting this!

**Comment by iRyusa** [comment]
Hi,

It should be ok for the next release of MJML cc https://github.com/mjmlio/mjml/commit/ce28f41d4a1081c1111501f1b8f356024722c3b5

**Comment by iRyusa** [comment]
It's now fixed in MJML3 sorry about that !
