### ISSUE TITLE
Margins completely different

### ISSUE THREAD

**Issue by joaopvilla** [mjmlio/mjml#38]
Why this margins are completely different? (Why content exceeds those margins?)

![aeed2020-ce81-11e5-8085-368a10b5687b](https://cloud.githubusercontent.com/assets/17101231/12945606/c34b6cb6-cfd5-11e5-986f-616e00110014.jpg)

**Comment by arnaudbreton** [comment]
Hi @joaopvilla, we need to dig deeper into that to understand what's wrong here. Keep you posted!

**Comment by iRyusa** [comment]
After some test @joaopvilla , we conclude that gmail has some built in margin of 15px and we cannot do anything about it.

Here's an example of your email with some background-color to understand what happens thanks to @hteumeuleu : https://www.emailonacid.com/app/acidtest/display/summary/5tNETiRyIorGzAnFR814fVqH4LEUtsjCQus6YyyduCAVO/shared

I am closing this one because it's a email design issue.

**Comment by Tlapi** [comment]
@iRyusa Can you please provide email source code so we can test it as well?

**Comment by iRyusa** [comment]
You can find the related MJML in #20 @Tlapi
