### ISSUE TITLE
mj-list not rendering in try-it-live on Firefox

### ISSUE THREAD

**Issue by simongareste** [mjmlio/mjml#404]
With Firefox 49, on a mac (Sierra), https://mjml.io/try-it-live/components/list/ does not show anything on the right pane. Work on Chrome on the same machine -> probably browser related?

Examining with the dev tools shows not error in the console, but an empty head and body in the right pane, in the iframe.

How to reproduce: with the following (Default try-it-live content for this component), or directly going to https://mjml.io/try-it-live/components/list/

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-list>
            <li>Go to the store</li>
            <li>sleep</li>
            <li>eat</li>
            <li>sleep again</li>
          </mj-list>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by ngarnier** [comment]
Hey @simongareste, thanks for reporting! 

I think this issue is actually happening for any MJML on Firefox. HTML is not rendered until a first edit to the MJML is made. This is a known issue, we need to dig it to see how we can solve it.

As a workaround, just do a simple edit to the MJML and it should render.

**Comment by simongareste** [comment]
Indeed, my bad.
