### ISSUE TITLE
adding another click to mj-carousel - feature request

### ISSUE THREAD

**Issue by hjoertel** [mjmlio/mjml#442]
if attribute thumbnails="hidden" is set and the email client is not able to display left- and right-icon a simple click on the image should move through the images. Advanced feature, left-click scrolls left and right click scrolls right

**Comment by ngarnier** [comment]
Hey @hjoertel, thanks for opening this issue. 

Unfortunately, when we're not displaying the left and right icons, it's because we can't enable the reader to browse through the images by clicking (in those cases, browsing through the images will generally be possible by hovering on the thumbnails). The fallback here if thumbnails are not displayed is to just display the first image. 

I have to close this issue as we have no workaround to implement that, sorry!
