### ISSUE TITLE
Hubspot Email rendering issues

### ISSUE THREAD

**Issue by JakeHenshall** [mjmlio/mjml#448]
Hi,

When sending the email from Hubspot it seems to show the mobile / responsive stacked layout even though the width is set to 600px in HubSpot and the email has a width of 600px. Does anyone know anything about this? I've tested the outputted HTML template in litmus and I don't get any issues.

any help is much appreciated.

Thanks Jake.

**Comment by ngarnier** [comment]
Hey @JakeHenshall, thanks for opening this issue. It would really help to have more information as detailed in [contributing.md](https://github.com/mjmlio/mjml/blob/master/CONTRIBUTING.md#template-for-submitting-bug-reports). Can you please at least provide: 
- MJML used
- MJML version used
- In which email clients you're seeing the mobile layout

Also, have you tried to compare the HTML outputted by MJML and the HTML sent by HubSpot to see if they might mess with the HTML before sending it?

**Comment by JakeHenshall** [comment]
@ngarnier Thanks for the reply.

MJML - Latest Version
In which email clients you're seeing the mobile layout - Gmail - Browser Version on Chrome is what we are seeing the problem in. Everything else looks brilliant

Now if you remove/comment out the code below this is what makes it go from the 2 column grid to the stacked layout. Do you know if there maybe a fix to this, also is they a way to make it non-responsive for testing purposes?

    <style type="text/css">
        @media only screen and (min-width:601px) {
            .mj-column-px-600, * [aria-labelledby="mj-column-px-600"] { width:600px!important; }
            .mj-column-px-300, * [aria-labelledby="mj-column-px-300"] { width:300px!important; }
        }
    </style>

Thanks Jake.

**Comment by iRyusa** [comment]
Hi @JakeHenshall you can just remove the media query or resize your browser to have the "stacked version" of your email.

>My issue seems to be the same as #24 as we are using Gmail for Work, has there been a work around for this?
>
> But for me the email is stacked on my Work Email and also Personal Gmail, but when I look at it in my email app called Newton they are both displaying fine, but are not responsive?

I think your issue is different,  gmail & g-suite do support media queries now so it won't happens anymore. 

Where did you copy the media query from ? it should be `min-width: 480px` and not `601px`

**Comment by iRyusa** [comment]
Hi @JakeHenshall any update on this ?

**Comment by iRyusa** [comment]
I'm closing this for now, feel free to reopen !

**Comment by SikMuse** [comment]
I came across a similar problem with columns not being respected in Hubspot - they were pushing my media queries way down and modifying my HTML. 

Discovered the following piece of documentation with resolved the issue for me: http://designers.hubspot.com/docs/cos/email-template-markup

My final recommendation is to take your HTML output and upload as a **coded file** in HubSpot, instead of trying to insert it in a Custom HTML module - this resolved all isues and stopped HubSpot from modifying the media queries and injecting their ASCII art...
