### ISSUE TITLE
Pass variables to templates

### ISSUE THREAD

**Issue by MatasSim** [mjmlio/mjml#451]
It's a feature request. it would be super cool if we could pass variables to included templates.
Something ike this `<mj-include path="/src/components/signature" track_id="1" />`

**Comment by iRyusa** [comment]
Hi @MatasSim 

This is something has been asked before and we don't want to variable inside `mj-include`. If we allow variables, people will ask conditionnal structures and MJML will become a templating language rather than a markup language.

My best advice for this : use a gulp workflow to render partials rather than `mj-include` and a templating language like mustache / handlebars to take care of templating needs

**Comment by MatasSim** [comment]
Ok, thanks for the answer. I'm currently using gulp to render/watch templates.
