### ISSUE TITLE
Padding on mj-section applied twice

### ISSUE THREAD

**Issue by okeegan** [mjmlio/mjml#460]
[**Example here**](https://mjml.io/try-it-live/Hkl7dRmme)

Hi there, it appears that applying padding with mj-class on an mj-section causes it to be applied to both the outer td (line 130 of compiled HTML) and also the inner td (line 135 of compiled HTML). I couldn't find an existing issue relating to this, but [this PR](https://github.com/mjmlio/mjml/pull/331) might be related?

**Comment by iRyusa** [comment]
Hi @okeegan 

You're nesting section inside a column. Every element that live inside a `column` will be wrapped in a `td` : that's why it's applied twice. However nesting a section in a column is forbidden.

What you want to do is add gutter to `mj-column` and we're working on it #160 . In the meantime people are using blank column with a spacer to achieve this, this is not sexy at all but it works.

I'm closing this one because it's not an actual bug.

**Comment by okeegan** [comment]
Thanks for the pointers @iRyusa! I guess I have some changes to make 😅. Would it be appropriate for me to make a PR and update the docs to specify the nesting incompatibility? I wasn't able to find that info in the mj-section part of the docs.

**Comment by iRyusa** [comment]
I believe it was in mj-section/column, but it's in the getting started [here](https://mjml.io/documentation/#nesting). I think you can do a PR about it it should be written inside `mj-column` too !

If you're using atom you can use this plugin : https://atom.io/packages/linter-mjml to spot this. And if you're installing MJML on your desktop, you will be noticed when compiling a file :

```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column wrong-arg="wrong">
          <mj-section></mj-section>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

will display : 

```
Line 6 (mj-section) — mj-section cannot be used inside mj-column, only inside: mj-container
```

**Comment by okeegan** [comment]
Ah perfect, installing now. Thanks again for your help!
