### ISSUE TITLE
Add mjml documentation as a user-contributed Dash docset 

### ISSUE THREAD

**Issue by manicmarvin** [mjmlio/mjml#508]
[Dash](https://kapeli.com/dash) is an API Documentation Browser and Code Snippet Manager.It would be tremendously useful to users of Dash, if we could add a docset to their repository for mjml.

Dash has a guide for [Docset Generation here](https://kapeli.com/docsets) and instructions for contributing the docset [here](https://github.com/Kapeli/Dash-User-Contributions)

**Comment by ngarnier** [comment]
Hey @manicmarvin, 

Good suggestion, thanks. Actually, @jaypeedevlin kindly proposed to add it and we definitely appreciate the help! I don't know if you have any news Josh?

**Comment by iRyusa** [comment]
As there's no contribution for now, let's close that, if anyone want to work on it, please let us know to re-open

**Comment by jaypeedevlin** [comment]
Apologies for going dark on this one — my recollection was that it wasn't clear to me what the MJML docs were built in, and unless it's one of the more common frameworks, building dashdocs becomes a much more cumbersome task.

As it happens, I'm now in a role where I have no regular use for MJML, so carving out time to make this contribution is difficult for me.

**Comment by julianrogmans** [comment]
I've been an avid user of Dash ever since I discovered it. Living with spotty internet access it has been invaluable for documentation reference when coding offline. I started searching for a MJML docset to use and found this issue. Seems like it's gone a bit stale but I'd be enthusiastic about trying to get something like this created. Anyone?
