### ISSUE TITLE
vertical space between stacked columns on mobile ?

### ISSUE THREAD

**Issue by ligne13** [mjmlio/mjml#576]
Hi,

is there a way to set a vertical space between two columns when they are stacked vertically on mobile ?

thanks

**Comment by ngarnier** [comment]
Hi @ligne13, I guess you want to have background colors on your columns and add a space to mark a separation between them (if not, please share a design so it's easier to understand what you want to do). You have several options here:
- Add the background color on the children elements of the column, and use a `mj-spacer` to add spacing below the first column (so it's between the 1st and the 2nd column).
- Add a column with a 0px width between the 2 column, in which you'll just add a `mj-spacer` (you'll notice there's an issue with this solution on Outlook but it's related to a bug we introduced in v3.3.0-beta, it will be fixed in the next beta release)

You can see a demo of those 2 solutions here: https://mjml.io/try-it-live/HySS4Lr9x

Hope it helps!

**Comment by ligne13** [comment]
Hi @ngarnier , thanks for these both solutions, that's exactly what I was looking for.
