### ISSUE TITLE
Section inside Column

### ISSUE THREAD

**Issue by bassbump** [mjmlio/mjml#580]
I have this example: https://mjml.io/try-it-live/ByD4mA95x

In this example I have used `<mj-column><mj-section><mj-column></mj-column></mj-section></mj-column>` to get the desired layout that I was looking for.

However, this is not valid according to mjml.io. May I ask why? I don't think my layout is that obscure, it seems a really common pattern to have use cases where you need columns in columns, and where `<mj-table>` doesn't work cause it only accepts html, we are back to coding html at that point.

If I ignore the errors, it also seems to compile and render fine.
Imo this kind of pattern needs to be possible in mjml.

**Comment by dalefish** [comment]
You've got column nested in section nested in column nested in section.
That is the invalid part.

You need to stick to Section->Column (up to x4) ->Element.

For that layout, you'd need:

<mj-section>
<mj-column></mj-column>
<mj-column></mj-column>
<mj-column></mj-column>
</mj-section>

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by ngarnier** [comment]
The issue here is that @bassbump wants to have the top of the 2 column stack onto the top of of the 3rd colum, and the bottom of the 2nd column stack on the 3rd  column. If he follows the valid MJML pattern the 2nd column will simply stack over the 3rd column:
![](https://puu.sh/uwvHY/5997c602fd.png).

We usually don't recommend nesting sections into columns because edge cases can lead to issues, but are you seeing rendering issues after testing in email clients? 

Otherwise, the table seems the safest way to go.

**Comment by iRyusa** [comment]
Closing this issue, because I don't think there's anything to do on that.
