### ISSUE TITLE
Background position

### ISSUE THREAD

**Issue by MichalCerny** [mjmlio/mjml#59]
Default in section is set to "top center" why is not working with background-position="X Y" ? Like that. 

`background: 'url(${mjAttribute('background-url')}) ${mjAttribute('background-position')} / ${mjAttribute('background-size') || ''} ${mjAttribute('background-repeat') || ''}'
`

**Comment by iRyusa** [comment]
Hi @MichalCerny , 
Most of client doesn't support `background-xxx` attributes, so we're merging them into  `background` who's almost supported everywhere ( outlook 20XX supports only VML ).

**Comment by MichalCerny** [comment]
I know, I dont want support of position in build, I need to setup position in merged background because default is top center .. i need center right or center left.

**Comment by iRyusa** [comment]
Oh... My bad.
If I remember correctly it's because we doesn't find a way to support it on outlook so it's by default top center you're right..
I guess we can add it, but add a warning in the documentation

**Comment by MichalCerny** [comment]
And what about background color together with image?

**Comment by gabskoro** [comment]
I also would appreciate support for background-image with background-color on `mj-section` elements

**Comment by ngarnier** [comment]
Hey @MichalCerny @gabskoro, about `background-image` support with `background-color`, it was [merged](https://github.com/mjmlio/mjml/pull/277) in 2.1.1.

The default top-center position still is an issue because of the lack of support in Outlook that @iRyusa explained.

**Comment by gabskoro** [comment]
Tnx :) 👍

**Comment by iRyusa** [comment]
With not enough support on background attributes ( like outlook/outlook.com & yahoo ) I am closing the issue. Feel free to reopen if needed !

**Comment by bsebastian81** [comment]
@iRyusa 
Without the ability to position the background, this is really a blocker for some layouts. Is there a hack to position the background anyway?

In this example we had to switch to graphics although it would be easy to solve with a background-position:left...
![label](https://user-images.githubusercontent.com/18003567/44847018-6cf39a80-ac52-11e8-9c2c-831fa19e61fa.png)

My approach would have been: Complete background graphic in 600px width and white text as content.  Fallback = Section has background color as in the graphic so that the white text is readable even if the graphic is not loaded.
**Problem:** Does not work responsive because the background is positioned in the middle. On a smartphone, the white text then moves over the white part of the background. I guess it would work if the bg would be positioned left.

**Comment by iRyusa** [comment]
I think this could be done with a mj-table ( first td your text & second an image/css trick to do this shape ). 

The support is still lacking so there's no really much to add here. You can play a bit with  `<mj-style inline="inline">` if you want to apply it manually, but you're on your own about the client fallback & support.
