### ISSUE TITLE
[Feature request] Fill entire background with color 

### ISSUE THREAD

**Issue by ckissi** [mjmlio/mjml#594]
I would like to have a possibility to fill entire space behind the email with a solid color or picture.

**Comment by ngarnier** [comment]
What about `background-color` on `mj-container` @ckissi? https://mjml.io/documentation/#mjml-container

**Comment by ckissi** [comment]
@ngarnier Great, thanks, didn't notice ;) Now only the picture possibility is missing. Any plans on this?

**Comment by ngarnier** [comment]
You can add a background picture with `background-url` on `mj-wrapper` (so it's behind several sections) or `mj-section`. 

You'd like the image to fill the whole container? It would probably be unaesthetic as on some clients the background will fill all the viewport (Outlook 2003 for example) but on others it will only fill the width of the container (Windows 10 Mail for example)...

**Comment by iRyusa** [comment]
If we add this @mattez we'll have to make the documentation clear about it then. Having a background image on full email body will disallow any background on a single `mj-section` because you can't nest VML. One workaround is to put every `mj-section` in a full-width `mj-wrapper` (even if full width doesn't work in outlook )

**Comment by iRyusa** [comment]
I'm closing this one, now you can use mj-wrapper with a full width attribute to mimic the behaviour. Note that supporting background image everywhere is a tricky and not doable everywhere. In MJML4, `full-width`attribute will be supported even in Outlook.
