### ISSUE TITLE
Hotmail and Outlook

### ISSUE THREAD

**Issue by dearpete** [mjmlio/mjml#602]
I have accepted that Hotmail and Outlook Desktop defaults to mobile view, only issue I'm having...I would like the images within the column to then default 100% width (See attached). Is this possible? or can I add a background images to a column using the mj-hero?

**Comment by ngarnier** [comment]
Hey @dearpete, when you say Outlook Desktop defaults to mobile view, are you referring to Outlook.com? Because all other versions of Outlook should display the desktop layout, not mobile view.

Regarding your question: 
- Images are not scaling up on mobile, their width is set by the number of columns side by side on desktop, cf https://github.com/mjmlio/mjml/issues/263
- Hero is a section element, not a column element, so it might lead to some issues (but it's still worth trying!)

**Comment by dearpete** [comment]
Thanks @ngarnier,

Sorry referring to Outlook.com, which shows the mobile version the desktop browser. 
1. Would be great if the images are fluid on mobile (100% width). Thanks for ref #263 
2. I'll give it a try! Thanks again for the support.

**Comment by ngarnier** [comment]
Indeed Outlook.com is the only major email client that shows the mobile version in desktop layout, because there's no way to make a distinction between mobile and desktop. 

Thanks for your answer, I'm closing!

**Comment by philspbr** [comment]
Is there any workaround for this? Ink/Foundation was showing the desktop version on Outlook.com with no issues. In Brazil, Outlook.com (i.e. former Hotmail) is still one of the most popular email providers, so it would be nice to be able to show the desktop version for those customers.

**Comment by ngarnier** [comment]
Hey @philspbr, OWA doesn't enable to differentiate between their mobile and their desktop client, so we choose to always display the mobile layout by default (which means mobile layout on desktop). The other way is to display desktop by default, but that means that users on mobile would see the desktop layout (which would be unreadable).

You can still target Outlook.com by using the `[owa]` selector if you want to have the desktop layout instead (copy the desktop media queries and them inside that selector).
