### ISSUE TITLE
Html substitution  and RCF standards.

### ISSUE THREAD

**Issue by lrae24** [mjmlio/mjml#617]
Hi Guys ,

Currently i am using mjml to substitute html in freemarker templates and what tends to happens  the newly created html seem to break the RCF2822/RCF 5322 protocol  where the line of characters should not exceed the limit of 998 characters per line.

Currently I am using postfix and if the line length is longer than the standard  specified in  RCF2822/RCF5322 protocol   then postfix will automatically truncate the lines which then can be at any point in the mail  causing  various errors the main one being  text not displayed  as the html tag itself can get truncated so the closing tag could be cut off. This did happen before  however we had found a solution whereby if we just added the line breaks in the mj-text tags for the column, that was exceeding the limit , that seemed to solve the issue but after  your Version 3.3.0 update that solutions no longer fixes this issue.

Can you guys fix this to adhere to the standard ?

**Comment by iRyusa** [comment]
Hi @lrae24

It looks really really specific to me, can you have a template to share that have this limitation ? I think that limit can happen if the HTML is minified... Can you test with non-minified HTML to see if it's ok ?

To be honest it can be fixed with a simple gulp task like this:  `compiledMJML.replace(/(.{998})/g,"\n$1")` However it can break things if the 998th chars is a tag or something.

**Comment by lrae24** [comment]
@iRyusa  the html I have seems to be minified so how would i change that ?

**Comment by iRyusa** [comment]
How do you render your MJML ? With cli/gulp/... ? Thanks !

**Comment by lrae24** [comment]
We use gulp .

**Comment by iRyusa** [comment]
From what version you've updated ? I think we didn't change the minify default option from a long time... 

Well, `gulp-mjml` will be updated soon to `2.1.1` and you'll be able to pass extra option like `{ minify: false }` to prevent this behaviour

**Comment by lrae24** [comment]
We upgraded from  3.2.2 to 3.3.0 , and is there no work around or fix that you guys have for this issue ?

**Comment by iRyusa** [comment]
I'm a bit surprised that you have some change in minification process from 3.2.X to 3.3.0. It still set to false by default. 

So it shouldn't be an issue, can you share your gulp file or something ?

To be honest, I never encountered this issue and neither familiar with Freemarker environment too... You could use something like gulp-html-beautify https://www.npmjs.com/package/gulp-html-beautify that will reindent everything for you, and i think there's a line-length's option too

**Comment by lrae24** [comment]
@iRyusa  i will definitely have a look at that solution and then get back to you if it works  or not  and with further details . However i would like to ask you  , is what was mentioned in this thread  replaced as this indicates that  minify is enable and even if i look at the current file you guys have  on github it still seems like you guys are using minify on the  templates.


https://github.com/mjmlio/gulp-mjml/issues/13.

**Comment by iRyusa** [comment]
We're providing a `minify` option as well as a `beautify` option that is disabled by default. ( because you have to activate it with with `{ minify: true/false }` as 2nd parameters to the `mjml2html` function.

Please note that we're using `React` internally and outputted HTML comes straight from React, so it's probably why the outputted HTML looks minified but in reality it doesn't, it's just how React output it.

We did change something related to how we're parsing MJML input (mostly cleaning stuff to avoid bugs with special characters) so it probably strips out your line breaks, and in result you don't see them in the final output.

**Comment by lrae24** [comment]
@iRyusa thanks will get back to you on this   after checking out the beautify solution with details.

**Comment by lrae24** [comment]
@iRyusa the html beautify plugin works well thanks.

**Comment by iRyusa** [comment]
👍
