### ISSUE TITLE
Full width mj-image inside a column

### ISSUE THREAD

**Issue by thomiduvigneau** [mjmlio/mjml#638]
`<mj-column width="50%"><mj-image src="placeholder.jpg" /></mj-column>`

Renders a td with width 300px (half of the container width). Is it possible to have an output of width 50%? The reason I'm asking this is because I want full width images at the mobile breakpoint instead of only 300px wide. I tried to fix this by doing the following:

`<mj-image width="100%" src="placeholder.jpg" />`

But that renders an image with width 100px instead of 100%.

**Comment by iRyusa** [comment]
Hi @thomiduvigneau 
This is something we're working to improve on MJML4. `mj-image` doesn't support percentage based unit, so that's why you're having a weird result. Making full-width mobile image while keeping a fixed width on desktop without a media query is quite paintful ( because of our beloved Outlook desktop ). 

I'm closing this issue because there's already a similar issue open, and we'll update there #263 !
