### ISSUE TITLE
mj-include: Add placeholders/variables

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml#653]
I found no practical way yet to use an external templating engine and think that this would really be helpful.

**Comment by iRyusa** [comment]
Hi @janus-reith 

Some people have some successful workflow with handlebars & other templating framework. We don't want MJML to become "another templating language". While giving variables people will want conditionnal structure & so o on. 

Can you share maybe your current setup so we can try to help you ?

**Comment by janus-reith** [comment]
Just wanted to give an update and saw your post,
I actually found a workflow with handlebars that works.
The default handlebars cli tool was not capable of simply outputting direct html or mjml syntax code,
but I found render-cli on npm which does what I need.

Closing this.

**Comment by roibeart** [comment]
If someone is still interested, I made a mjml component that allows to use variables without the need of an external template engine:
https://github.com/roibeart/mjml-wb-variable
Probably the programming logic beneath it is unconventional and quite dirty, but it works well and saved me a lot of hassles.

**Comment by vaguedread** [comment]
Hi @roibeart 

I'd like to use your component but unable to get it to work. It's likely I haven't installed it properly. Is there something more to installing beyond copying the lib folder (which only contains the .gitkeep file) and the .mjmlconfig file into the mjml project folder? What about all of the other files in the mjml-wb-variable repository?

Thanks for any help getting this working.

**Comment by roibeart** [comment]
Hi @vaguedread, thanks to your report I realized that the lib folder didn't have the compiled file of the component...
I added it now to the repository, if you copy it to your project the component should work.
Sorry for the inconvenience! Let me know if you need more support.

**Comment by vaguedread** [comment]
Hi @roibeart 
Thanks for responding. I'm still unable to get it to work. My installation is probably not correct since I continue to get the message that wb-variable "doesn't exist or is not registered." Attached, a screengrab of where I installed the files.
![variable-install-issue](https://user-images.githubusercontent.com/14594212/38896534-f4a82f38-4260-11e8-908c-23ca7b234348.gif)

Also, the directions say to declare the variables within the mj-container. According to the mjml documentation, that component is no longer valid in v4. I tried placing my variables just below the opening mj-body tag, but no luck. What am I doing wrong?
