### ISSUE TITLE
Switch the image depending on the screen size (Responsive Design)

### ISSUE THREAD

**Issue by iwanaga-sakura** [mjmlio/mjml#654]
Is it possible to switch two images depending on the screen size?

```
<mj-column>
   <mj-image src="sp.png"></mj-image>   //Show this image if the screen size is between 1px and 480px
   <mj-image src="pc.png"></mj-image>   //Show this image if the screen size is more that 481px
</mj-column>
```

I used the media queries after compiling the mjml but the `display:none;` is also not working and I thought I wasn't on the right track.

**Comment by ngarnier** [comment]
hey @iwanaga-sakura, you'll have to use a media query for that, however this kind of approach isn't recommended because some email clients won't support them and display both images. 

Raw demo (even though you'd probably want to display/hide the whole `tr` the image is contained in and not just the `img`: https://mjml.io/try-it-live/ryb8-bA0x

**Comment by iwanaga-sakura** [comment]
@ngarnier Thanks for the live Demo!
Seems like it won't work on all browser.
Glad that I get to know that.
Thanks a lot!
