### ISSUE TITLE
The lang property in the HTML tag is disappearing

### ISSUE THREAD

**Issue by leandromatos** [mjmlio/mjml#689]
I need insert a lang property in html tag, i tried `<mjml lang="ar">` but, not work. After mjml build html this lang property disappeared.

An someone help me? I am building emails in Arabic and need to insert this tag in html.

Thanks

**Comment by ngarnier** [comment]
Hey @leandromatos, which HTML tag do you need to add this attribute to? The best option for now is to add it to the raw HTML after compilation.

**Comment by leandromatos** [comment]
Initially I need to add in the HTML tag (the one that opens the document itself), but anyway it would be of great value if I could add in other elements, because there are some languages that are written in the sense "right to left" and for that would also be necessary Apply the dir attribute next to the lang.

See the specifications https://www.w3.org/International/questions/qa-html-dir

**Comment by leandromatos** [comment]
Other interesting article about rtl:

https://www.campaignmonitor.com/blog/email-marketing/2014/10/order-stacked-columns-responsive-email/

**Comment by ngarnier** [comment]
Hey @leandromatos, I'm asking you where you want to add it specifically because it's not that easy. One `mjml` tag doesn't equal only one `html` tag, so we'd have to better understand on which element you want those attributes to be added.

Also, I think what you're describing is already possible:
1. Using `rtl` on a text: you can do it by adding `dir="rtl"` to a HTML element inside `mj-text`
2. Using `rtl` to reverse the order in which columns are stacking: you can can do it by adding `direction="rtl"` to a `mj-section` (see the [documentation](https://mjml.io/documentation/#mjml-section))

I made an example so you can see an example of both use cases: https://mjml.io/try-it-live/B17o7CNZW

**Comment by ngarnier** [comment]
@leandromatos, so is the point of the `lang` attribute here for RTL support? If yes, I'll close in favor #230. 

Also, you might be interested in the workaround given in #230: 
```
  <mj-head>
    <mj-style inline="inline">
      * { direction: rtl; text-align: right !important; }
    </mj-style>
  </mj-head>
```

**Comment by ngarnier** [comment]
Hi, I'm closing as I didn't hear back from you @leandromatos, feel free to reopen if you think your issue isn't solved
