### ISSUE TITLE
full-width sections inside a full-width wrapper not working

### ISSUE THREAD

**Issue by mberhorst** [mjmlio/mjml#694]
My example:

```
           <mj-wrapper full-width="full-width">
                <mj-section full-width="full-width" background-color="#144492">
                    <mj-column width="100%">
                         <mj-text mj-class="font-big" text-transform="uppercase" align="center" font-weight="bold">
                            Text
                        </mj-text>
                    </mj-column>
                </mj-section>
                <mj-section full-width="full-width" background-color="#ffffff">
                    <mj-column width="100%">
                        <mj-text mj-class="text-blue font-big" text-transform="uppercase" align="center" font-weight="bold">
                            Text
                        </mj-text>
                    </mj-column>
                </mj-section>
            </mj-wrapper>
```

Problem: The full-width attribute does not work inside a wrapper which also has the full-width attribute.

The wrapper would be necessary for me to add some background-styling to it.

**Comment by iRyusa** [comment]
Hi @mberhorst 

This one is a bit tricky because you need to understand what's going on in the HTML produced by wrapper. To simplify this, a `wrapper` is behaving as a section. So full-width basically just extends the background to full width and not the content to full-width : content stick to the 600px ( or email width ). 

If you have a full-width section within a full-width section, the second one will get 100% width of the allowed width from his parent ( 600px then ) so that's why you can't extend a section full-width within a full-width wrapper.

Can you provide a screenshot of what you want to do with that ? Because I don't really understand why you would wrap multiple full-width section inside a wrapper.

**Comment by mberhorst** [comment]
Thanks @iRyusa 
I thought again about what I wanted to do and I came to the solution that its not possible, even with the full-width wrapper and the full-width sections. So problem solved I guess. But a note in the docs would be nice, that a section inside a full-width wrapper cannot be full-width too.

**Comment by iRyusa** [comment]
There's a notice in the doc now. It will be release on mjml.io/documentation among 3.3.4 release
