### ISSUE TITLE
Request: Support wider range of social icons

### ISSUE THREAD

**Issue by MissFerrety** [mjmlio/mjml#705]
I appreciate being able to select a background color for the icons, but do not like being limited to white-overlay rounded-box icons. At the very least, I would appreciate a fully-custom icon url setting (not just base). Other more dynamic options could include:

- list any other publicly available base url settings you recommend (following the default gives me a "too many redirects" error)
- border radius setting
- implement font awesome for mark-only icons

**Comment by iRyusa** [comment]
Hi @MissFerrety 

Appreciate the feedback on it while we working on new mj-social.

For base-url, you have to create your own base url with your own icons. (I think the server doesn't allow file listing that's why you have an error when trying to visit it ;) ).
Border-radius is coming to next release thanks to this pr #556 ! 
font-awesome isn't really "email-proof" so we don't gonna do anything on this part. I suggest you to do a custom component if you want to do so

I'm closing this one too because I think I've replied to everything, feel free to re-open if needed
