### ISSUE TITLE
Possible to Ignore Lines of Code by MJML? [Not Issue]

### ISSUE THREAD

**Issue by carstengrimm** [mjmlio/mjml#769]
I am quite new to MJML and I am very happy with the results i have gotten so far.

As of my workflow i am using the atom plugin and linter to write my mjml files which is by far the fastest way (for me to get an responsive email template done). (on just another matter it's too bad that the atom plugin does not provide html output so i am always manually using the mjml app for this occasion.

for the most part, i am also able to directly write some PHP inside while when generating html it'll still keep it like that... for example simple echo this and that... sometimes it'll convert the dollar symbol to html safe but that can be easily replaced searching thought the html code.

it's really too bad when i am using other statements such as a foreach loop between sections, or between columns - that those are not kept at all after converting to html... so i have to manually add them to the html code later to make it work.

that's the reason to open that suggestion,... is there any way to make the mjml processor within the app ignore certain lines? e.g. i have been trying to comment  but this also doesn't seem to keep.

other than that i am also open for suggestions on how to change my workflow to make things a little bit more automatic... 

unfortunately my email templates will get used as html and at least at current ways there's no method preprocess the php before the mjml. but who knows what ways are available there. maybe there's a way to turn mjml to html on the fly where my php code will loop some columns first, mjml then gets processed and outputted to my (phpmailer) client...

**Comment by iRyusa** [comment]
Hi @carstengrimm 

I think you need to use `mj-raw` for that, but care with loops, it could break the layout if you're looping on `mj-column`

There's still some bug with `mj-raw` atm, that can only be solved in MJML 4 see #600 

I'm closing because mj-raw fit your needs, but keep in mind you can still encounter issues with it

**Comment by holmesadrianh** [comment]
I am not to worried about where to place the mj-raw tag, I am just hoping to get custom code to remain at the top of the rendered document. And to be clear, before the <!doctype html>. Literally right at the top.

The reason is I am working with backend developers who need their own code at the root of the email templates with various snippets with logic and variables which needs to remain untouched. I am hoping for a workflow because there are so many email templates required and using MJML would be ideal.

Even if it could work like so:
<mjml>
  <mj-raw>
    Unaffected code kept at the root of the document.
  </mj-raw>
</mjml>

If this cannot be done, could you suggest an alternative where I create a custom task with the likes of Grunt for instance? 

Perhaps there is a way to have my own custom tag in the MJML template at the root which I take out to store in a variable to add back after MJML processes the template?

Or even if there was something like <mj-ignore> that saved the snippets in an array and keeps reference with the likes of a template tag like %%IGNORE1%% or $0 or something along those lines to add back after MJML finishes the compiling.

I know it might not be ideal, but I can understand what MJML needs to solve which I believe would be tricky to implement something as per my request.

Any advice or feedback would be much appreciated.

Adrian

**Comment by dalefish** [comment]
If you are working directly with developers, adding a line or code block
prior to the html element via grunt/gulp should be simple enough.

There are no required changes to MJML to make this happen, just​ a little
thought.


On 24 Jul 2018 17:58, "holmesadrianh" <notifications@github.com> wrote:

I am not to worried about where to place the mj-raw tag, I am just hoping
to get custom code to remain at the top of the rendered document. And to be
clear, before the <!doctype html>. Literally right at the top.

The reason is I am working with backend developers who need their own code
at the root of the email templates with various snippets with logic and
variables which needs to remain untouched. I am hoping for a workflow
because there are so many email templates required and using MJML would be
ideal.

Even if it could work like so:


Unaffected code kept at the root of the document.

If this cannot be done, could you suggest an alternative where I create a
custom task with the likes of Grunt for instance?

Perhaps there is a way to have my own custom tag in the MJML template at
the root which I take out to store in a variable to add back after MJML
processes the template?

Or even if there was something like that saved the snippets in an array and
keeps reference with the likes of a template tag like %%IGNORE1%% or $0 or
something along those lines to add back after MJML finishes the compiling.

I know it might not be ideal, but I can understand what MJML needs to solve
which I believe would be tricky to implement something as per my request.

Any advice or feedback would be much appreciated.

Adrian

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mjmlio/mjml/issues/769#issuecomment-407459032>, or mute
the thread
