### ISSUE TITLE
MJ-COLUMN IOS 9 ISSUE

### ISSUE THREAD

**Issue by lrae24** [mjmlio/mjml#776]
Hi guys , 

Not 100% sure  but i noticed that there seems to be an issue with the columns in a mj-group on ios 9 .
![screen shot 2017-08-14 at 4 03 15 pm](https://user-images.githubusercontent.com/25219824/29275061-256cdb00-810a-11e7-98e5-5860ccabc196.png)

Acording to your documentation is says in the output html remove the blank space in between the 2 columns in the group i can't seem to find the mj-group in my output and initially we just converted and replaced our ftl files.However we noticed that the line length got too long and broke some of our templates i then added html beautify and html trimlines so there is no space between the elements. Each element does open and close on a new line though is there a way around this issue in mjml or can something else that can be done ? The screenshot shows my html ouput and  if i am not mistaken that is a complete mj-group  with 2 columns.

**Comment by iRyusa** [comment]
Hi @lrae24 

Can you provide the MJML from your screenshot, i'm worried about the NaNpx in the `td`.

On your issue, MJML cli provide a minify option ( `-m` ) that does the job automatically for you. Mj-group implementation is almost the same as an mj-column, main difference is the `width` of mj-columns within a group. That's why you don't see any reference of mj-group in the output HTML. Note that `endline` can count as a blankspace too.

You can tweak some options on the engine [(here the lib we're using in MJML)](https://kangax.github.io/html-minifier) to avoid your line length issue. Here's the default options we're using : https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/MJMLRenderer.js#L48

**Comment by iRyusa** [comment]
I'm closing this issue for now, feel free to reopen if it doesn't work for you
