### ISSUE TITLE
Multiple columns are shown as mobile on desktop (below each other)

### ISSUE THREAD

**Issue by TisLars** [mjmlio/mjml#823]
I expect the columns to be next to each other, as it is shown when I view the e-mail template on my local environment.

The following code snippet is used: https://mjml.io/try-it-live/BJ2h2Yci-

I viewed the e-mail in Outlook (https://outlook.live.com) and Inbox Google (https://inbox.google.com/).

Is it an e-mail service issue or am I doing something wrong with MJML?

**Comment by iRyusa** [comment]
Hi @TisLars 

On outlook.com this is the expected behavior because we can't tell the difference between mobile and desktop outlook.com. If you want to display as desktop, you copy paste every class .mj-column-* in the media query and prefix it with a `[owa]` selector. But then mobile outlook.com will display it as desktop too.

For Inbox I believe it now supports media queries, so how did you send the email ?

**Comment by TisLars** [comment]
Hey @iRyusa 

I used both [Litmus PutsMail](https://putsmail.com/) and MailChimp to send my newsletter. In both cases my columns were below each other. I think I will go for `<mj-group>...</mj-group>`. This way the columns are all next to each other, no matter what device.

Thanks for verifying it has to do with e-mail service.

**Comment by iRyusa** [comment]
Well, it does work fine for me with bare examples (https://mjml.io/try-it-live/templates/racoon)
![image](https://user-images.githubusercontent.com/570317/31072899-1eb79df0-a76a-11e7-8c5c-a540b612ce33.png)

We know that MailChimp alter the HTML output, some people did succeed to send MJML emails through MailChimp but I don't recall how they've done it.

You should be careful when using `mj-group` because every mobile clients won't stack column anymore, and it could make your email totally unreadable on mobile
