### ISSUE TITLE
Blank screen on the desktop app

### ISSUE THREAD

**Issue by nvassos** [mjmlio/mjml#864]
Hey guys, did you encounter the issue where while you are working on the actual app *tried both OS X and Windows Versions* it becomes blank and you need to restart the app all the time? That's after updating on version 2.7.

**Comment by meriadec** [comment]
Hey @nvassos, as it is a problem specific to mjml-app, would you mind re-create the issue on [the mjml-app](https://github.com/mjmlio/mjml/issues/864) repo? Thanks. Can you also specify the eventual clues that can help (e.g: opening file inside a DropBox folder, etc.), because I did'nt reproduced the issue on OSX version on my side.

As a quick workaround, I hope that downgrading to older version works for you. Have a good day.
