### ISSUE TITLE
Compatibility with templating engines

### ISSUE THREAD

**Issue by martixy** [mjmlio/mjml#881]
I use MJML for emails in a workflow that includes nunjucks/twig style templating.
Rendering variables(+contatenation) looks like this:
`{{ variable ~ 'words' }}`

I noticed that this case generates garbage with mjml:
`{{ var ~ '<word' }}`

Notice how this looks like an open tag. Not even a complete one. Well, mjml v3.3.0 auto-closes this non-tag somewhere down the line in its generated code. v3.3.5 _additionally_ butchers the code immediately surrounding the malformed tag as well.

Would this be considered a bug? One resolvable on mjml's part? Or would it be left for template users to work around ourselves?

**Comment by iRyusa** [comment]
Hi @martixy 

Yes this is a known bug sadly in MJML parser, it produces sometimes some random opening tag when encountering chars like `<`/ `>`/...

It will no longer be an issue in MJML4 because we totally rewrite the parser. In the meantime you should replace every `<`/ `>` with the ASCII HTML counterpart `&lt;` `&gt;`, they will be decoded in the final output and should prevent this behavior.

I'm closing this issue because there's already an issue opened on that #394 :)
