### ISSUE TITLE
Problem with the columns position in Outlook 2010 and 2013

### ISSUE THREAD

**Issue by jojape** [mjmlio/mjml#900]
Hi there,

I have problems with the columns positions in Outlook 2010 and Outlook 2013.
Expected appearance: https://drive.google.com/file/d/1vb7fNcineCMoUetHNFFvGBLfbOhdbcTV/view?usp=sharing
Appearance on Outlook 2010 and 2013: https://drive.google.com/file/d/1TR_soNw4MnboR9jEeWktxgefOvqQVCgj/view?usp=sharing

MJML version: https://drive.google.com/file/d/1QnnwqUvOK5ei6YOaYTMl0lg_Jhxp2SUq/view?usp=sharing
I tried pasting here all the code, but it's not displayed at all.

      **Email clients the bug is seen on:**

      Outlook 2010 and Outlook 2013.

**Comment by ngarnier** [comment]
Hey @jojape, we'll need the MJML code here. 

Can you try again pasting it, or paste it on the try it live and share a link to your snippet (a custom URL will be created when you paste your code): https://mjml.io/try-it-live

**Comment by jojape** [comment]
Hey Nicolas,

https://mjml.io/try-it-live/B1Qzqb2xf this is the code.

Thank you.

**Comment by jojape** [comment]
Hey Nicolas,

https://mjml.io/try-it-live/B1Qzqb2xf this is the code.

Thank you.


On November 29, 2017 at 11:20:22, Nicolas Garnier (notifications@github.com)
wrote:

Hey @jojape <https://github.com/jojape>, we'll need the MJML code here.

Can you try again pasting it, or paste it on the try it live and share a
link to your snippet (a custom URL will be created when you paste your
code): https://mjml.io/try-it-live

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mjmlio/mjml/issues/900#issuecomment-347815850>, or mute
the thread

**Comment by ngarnier** [comment]
hey @jojape, the total of the column widths for a section should be 100% maximum, here your section as a width of: 30 + 70 + 100 + 100 + 60 + 40 = 400%. 

Make sure to split your columns into sections, for example: 
- 1 section with columns of 70% + 30%
- 1 section with columns of 100%
- 1 section with columns of 100%
- 1 section with columns of 60% + 40%

Makes sense?

PS: sorry for the previous comment, didn't see you linked the MJML on Google Drive

**Comment by jojape** [comment]
Hey @ngarnier, thx so much. I just modified it with the structure you purposed me and it's workins as expected.
When I splitted them into separate sections, I have this issues:

- Increased the space between the text and the footer gray line (all email clients)
https://drive.google.com/file/d/1UkLo3TCfzbSxVS9U7BJ1h6pn3YoL1Okq/view?usp=sharing
- Increased social icons space (top and bottom) (all email clients)
https://drive.google.com/file/d/1UkLo3TCfzbSxVS9U7BJ1h6pn3YoL1Okq/view?usp=sharing
- Social icons are not displayed properly (Outlook 2010 and Outlook 2013 - Desktop)
https://drive.google.com/file/d/1UkLo3TCfzbSxVS9U7BJ1h6pn3YoL1Okq/view?usp=sharing
- Displaying [UNSUBSCRIBE_LINK]in outlook.com (Chrome): https://drive.google.com/file/d/1bZtPpBsikW7tzfs6qpuTOGRyI8NtTEC5/view?usp=sharing

Thank you 👍

**Comment by ngarnier** [comment]
You're welcome. 

- You need to adjust the padding on your sections as there is a default padding on `mj-section`. You can either adjust it on each section manually or you can also use `<mj-all padding="0" />` inside `mj-attributes` to reset padding for all mj-elements (you can also use `<mj-section padding="0" />` to only impact sections and not all elements) 
- I don't understand the issue here, simply adjust the width of your table? 
- It looks like a `line-height` issue. As you are not using MJML but plain HTML here, you need to fix this on the HTML (by setting a greater `line-height` on `th`
- This doesn't sound related to MJML but rather your ESP. How are you sending? It seems like this variable is being added automatically, it's not in your original MJML template and MJML doesn't add that kind of content.

Additionally, you have errors in your code: 
- make sure to use `=` to set a value in `mj-attributes`, not `: ` (line 9 for example)
- the syntax for a breaking tag is `<br />`, not `</br>`
- your empty column line 99 is useless, simply use a single column with text aligned to the left and line breaks if needed

**Comment by jojape** [comment]
Thanks for helping me. I fixed everything unless:

- "It looks like a line-height issue. As you are not using MJML but plain HTML here, you need to fix this on the HTML (by setting a greater line-height on <th>)"

Code: https://mjml.io/try-it-live/HkkSOnAeG

**Comment by ngarnier** [comment]
You're setting a `line-height` as a HTML attribute (`th` is an HTML tag, not a MJML tag), whereas it's a style attribute. Here is how to do: https://mjml.io/try-it-live/r1JyF30gM

PS: You have an issue line 50, the `</a>` tag that shouldn't be here. You can identify these issues by the little red crosses on the left (I fixed it in the link above).
