### ISSUE TITLE
Gmx/webclients column problems

### ISSUE THREAD

**Issue by gaason** [mjmlio/mjml#905]
Hi!

Some webclients have problems with mobile first design.
E.g.: The mj-column-per-50 div has a width of 100% in the inline-style. In the css above it should be replaced with 50% at a viewport min-width of 480px. But actually this is not working.

Before:
![Image before ](https://image.ibb.co/js5U4b/before.png)

So I tried to replace the inline-style with 50% an I have set the `min-width` media-query to `max-width` and replaced the 50% with 100%.
Like this:
```
<div class="mj-column-per-50 outlook-group-fix" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:50%;">

@media only screen and (max-width:480px) {
    .mj-column-per-100 { width:100%!important; }
    .mj-column-per-50 { width:100%!important; }
}
```

Actually this is the only way, to get it work and it does not break the mobile functionality on e.g. a Iphone.

After:
![Image before ](https://image.ibb.co/dM4NPb/after.png)

**Comment by iRyusa** [comment]
Hi @gaason

We're aware that some local clients as gmx doesn't support media queries. But as MJML is a mobile first approach framework we prefer to display mobile version in desktop rather than desktop version in mobile.

If you want to do it, you can use some `mj-style` tricks with inline mode to replace the inline width with the width you want and add your modified media queries with mj-style after.
