### ISSUE TITLE
MJML Mac Desktop app not Downloading update

### ISSUE THREAD

**Issue by maherelaridi** [mjmlio/mjml#909]
Hi, 

**Observed behavior:**      
I am not able to update the MJML app. The Download Now button does not go anywhere. 

**Screenshots and GIFs**
![screenshot 2017-12-06 10 28 04](https://user-images.githubusercontent.com/2089136/33672745-9b1c9290-da70-11e7-8076-eac7742153f7.png)

**MJML version:**
- MJML App v2.4.0
- MJML v3.3.3

Thanks for your help!

**Comment by dalefish** [comment]
I think 2.7 was discontinued, you get get all versions here:
https://github.com/mjmlio/mjml-app

On 6 Dec 2017 5:34 p.m., "Maher El Aridi" <notifications@github.com> wrote:

Hi,

*Observed behavior:*
I am not able to update the MJML app. The Download Now button does not go
anywhere.

*Screenshots and GIFs*
[image: screenshot 2017-12-06 10 28 04]
<https://user-images.githubusercontent.com/2089136/33672745-9b1c9290-da70-11e7-8076-eac7742153f7.png>

*MJML version:*

   - MJML App v2.4.0
   - MJML v3.3.3

Thanks for your help!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mjmlio/mjml/issues/909>, or mute the thread

**Comment by ngarnier** [comment]
Hey, indeed as stated by @dalefish 2.7.0 was discontinued so there's no update. Just so you know for next time, mjml-app has its dedicated repo: https://github.com/mjmlio/mjml-app
