### ISSUE TITLE
Images aligning in columns on outlook

### ISSUE THREAD

**Issue by ketschi-max** [mjmlio/mjml#917]
Hello all,

When I send out a e-mail I get a problem with the aligning of 3 images in 3 columns in one section on outlook. They seem to be aligned to the left when they should be aligned in the center. 

The code that is being used for the section is as followed:

        <mj-section background-url="http://scnem.com/art_resource.php?sid=bjvj5.27dr730">
          <mj-column align="center" width="33.33333333333333%">
            <mj-image align="center" href="http://www.doyzip.com" src="http://scnem.com/art_resource.php?sid=bjvru.hcaj7"></mj-image>
          </mj-column>
          <mj-column align="center" width="33.33333333333333%">
            <mj-image align="center" href="http://scnem.com/art_resource.php?sid=bje2e.2bfi0n8" src="http://scnem.com/art_resource.php?sid=bjvrt.2h1bgdq"></mj-image>
          </mj-column>
          <mj-column align="center" width="33.33333333333333%">
            <mj-image align="center" href="http://solutions4value.com" src="http://scnem.com/art_resource.php?sid=bj5uw.qocmkd"></mj-image>
          </mj-column>
        </mj-section>

In Apple Mail for example the section is displayed correctly as followed:
![schermafbeelding 2017-12-12 om 14 36 02](https://user-images.githubusercontent.com/33489719/33887412-fb8df1f4-df49-11e7-8cc6-6791ce289cbd.png)

In Outlook e-mail client the section is displayed as followed:
![schermafbeelding 2017-12-12 om 14 35 54](https://user-images.githubusercontent.com/33489719/33887510-40efe306-df4a-11e7-8b65-9cd5a028a519.png)

Is there any way that I can get them to align in the middle as in my Apple Mail?

I have given the images the exact same dimensions.

Thank you in advance!

Kind regards,
Max

**Comment by iRyusa** [comment]
Hi @ketschi-max 

This is a known issue with padding <> vml background <> having multiple nested table in Outlook engine. We didn't find any workaround on that as you can read here :https://github.com/mjmlio/mjml/issues/128#issuecomment-312688536 . We have no control on this behavior. What you can do is removing the padding on every element inside your column and it should behave almost as expected.

I'm closing the issue (like #128) because it's a bug in Word Engine and not in MJML's HTML
