### ISSUE TITLE
Create a full width border

### ISSUE THREAD

**Issue by nicolas-besnard** [mjmlio/mjml#975]
Hi,

I'd like to create a full-width border for one of my `mj-section`, but the `border-top` attribute stops at the max-width of the column (600px I believe).

Is there a way to achieve that?

Here my current implementation: https://mjml.io/try-it-live/HyzdN9RSf

**Comment by ngarnier** [comment]
Indeed the border is applied on the `td` of the section when you want to apply it on its table. Simply using a `css-class` and using an inline style should do the trick: https://mjml.io/try-it-live/By5hBWkLf

You're not seeing it full-width on the try it live because the iframe is 600px, but if you save the HTML and open it elsewhere you'll see the border is full-width. Hope it helps!
