### ISSUE TITLE
W3C validation ?  (https://validator.w3.org/nu/)

### ISSUE THREAD

**Issue by martin-gillen** [mjmlio/mjml#980]
Not a problem report just a question.

I've heard that some mail systems will reject an HTML email that has "sloppy markup" (which is a vague term).

I ran an MJML email through the W3C validator and it found some issues like:
```
Error: Attribute xmlns:v not allowed here.
From line 1, column 16; to line 1, column 148
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
```
or
```
Error: Element title must not be empty.
From line 2, column 8; to line 2, column 15
<title></title>
```
Has anyone experiences MJML HTML emails being marked as spam due to an HTML validation check failing because issues like this?

**Comment by ngarnier** [comment]
Hey @martin-gillen, this won't cause the email to be rejected. About each point:

- `xmlns:v` is used here to use VML (Vector Markup Language) inside the email, which is necessary to display background-images on certain versions of Microsoft Outlook (2007, 2010, 2013)
- `Element title must not be empty`: this is a minor error, simply because the file has an empty title. You can fix it by adding a title: 

```
  <mj-head>
    <mj-title>My title</mj-title>
  </mj-head>
```

I'm closing as I think it answers your question, but feel free to comment if you have more.
