### ISSUE TITLE
mjml-button should have cursor: pointer

### ISSUE THREAD

**Issue by IchordeDionysos** [mjmlio/mjml#981]
Hi,
a `mj-button` should have the CSS attribute `cursor: pointer` so on Desktop there will be a Pointer indicating a clickable are, instead of the default mouse cursor.

E.g. Standard Link `a`-tags have a cursor in Inbox by Gmail

**Comment by iRyusa** [comment]
Hi @IchordeDionysos 

As button isn't fully clickable due to client support, giving a `cursor: pointer` on a non-clickable area would confuse the user. You can do so if you want through css class + mj-style but I think this is a bad practice. 

(And I don't really know about the `cursor` css support on mail clients too)

So I'm closing it
