### ISSUE TITLE
[Feature request / Question]: mj-layout component

### ISSUE THREAD

**Issue by Pentiado** [mjmlio/mjml#987]
I evaluate mjml as a tool for making my days less horrible when I need to do something with transactional emails and there is one feature - reusable layout that I can't find any informations of but I'm just sure there is a way how people do it nicely now. If not, then component mj-layout would be perfect for the job.

I used to write emails in pug and it was basic feature there. I know mjml wants to be a framework and not template engine but there is "mj-include" and mj-layout would be kind of reverse include.

Pseudo code explaining what I would like to achieve:

layout.mjml

    <mjml>
      <mj-head>...</mj-head>
      <mj-body>
         ... some header
         <mj-this-is-where-content-comes><</mj-this-is-where-content-comes>
         ... some footer
      </mj-body>
    </mjml>

welcome-user.mjml

    <mj-layout src="./layout.mjml">
      <mj-text>
         Hi user!
      </mj-text>
    </mj-layout>

I could split layout into few elements and use mj-include in each file but it feels cumbersome. I know I can write function that will take mjml file, wrap with some layout code, compile and return html but then I'm loosing power of your desktop app so creating new emails becomes less pleasant task...if creating emails you can ever call a pleasant task : )

-------------------------

If this feature is something you would be interested in and there is no better way for dealing with layouts I can spend some time on it next week.

**Comment by ngarnier** [comment]
Hey @Pentiado, 

Thanks for explaining your need clearly. 

Indeed, since the beginning of MJML, we committed to keep MJML a responsive-email framework and not a templating engine. The fact that you would like such a layout/block feature tends to confirm we did the right thing, as we knew that following the addition of simple variables, more requests would come for more and more advanced templating features. As you said, this is very easy to do with a templating engine like pug, so I think the solution is already there.

As you said however, it would be nice to have that in the app too. Then, maybe, rather than adding those features in MJML directly, it could be nice to have such features in the MJML App?

**Comment by Pentiado** [comment]
You welcome. By writing issues that are easy to read and understand I'm avoiding the trap of label "to be responded someday" : )

Yeah, it would be definitely nice to have it in desktop app. I'm just thinking if it's not kind of "dead end" solution. It helps me but it's just a matter of time until someone else asks template engine related question. I've just read through your closed issues and there is plenty of it. For my defense, before opening this issue I searched for "layout" keyword.

What about middleware like approach? Embracing MJML as a framework and accepting the need for template engine. MJML would take config params that could be provided directly to compile function or if there is a file in project called config-mjml.js (or whatever) it takes that as default. In config developer could specify functions that should run on specific stages of process like "before:compile", "after:compile" then in docs it would be easy to explain how to have access to features from template engines.

Consider it as brainstorm so it might be not the right approach but an attempt to find one. There is definitely a place for improvement on the line of engine/framework.

**Comment by iRyusa** [comment]
Hi !

About hooks on before/after compile, I don't think there's some need of it because you can pass directly the json to mjml2html, and an after compile is basically editing the html output. 

We're not totally closed to offer better tooling for developer, but I think there's already everything out there for now (gulp/grunt/brunch/...) instead of re-implement a worst pseudo task runner ?

**Comment by Pentiado** [comment]
Yes, it's actually a good point. Well, then I don't have better ideas for something universal that would work on desktop app and in code.

**Comment by ogonkov** [comment]
What is a difference from using custom elements?

**Comment by iRyusa** [comment]
You can also use multiple shared mj-include across your project ( mj-include can contain both mj-head & mj-body )

I think we can close this issue for now.

**Comment by equinusocio** [comment]
> We're not totally closed to offer better tooling for developer, but I think there's already everything out there for now (gulp/grunt/brunch/...) instead of re-implement a worst pseudo task runner ?

gulp/grunt/brunch basically all dead.
